const fs = require('fs');
const path = require('path');

const articlesPath = 'c:\\Users\\javit\\OneDrive\\Desktop\\2WEB\\src\\data\\articles.ts';

if (fs.existsSync(articlesPath)) {
  let content = fs.readFileSync(articlesPath, 'utf-8');
  
  const replacements = [
    [/gordinflamente obsoleta/g, 'obsoleta'],
    [/muñequito verde/g, 'Android'],
    [/maravillositas/g, ''],
    [/maravillosamente/g, ''],
    [/maravillosísimamente/g, ''],
    [/maravilloso/g, ''],
    [/maravillosísima/g, ''],
    [/maravillosas/g, ''],
    [/maravillosos/g, ''],
    [/gordinflón/g, ''],
    [/gordinflones/g, ''],
    [/gordinflona/g, ''],
    [/majestuoso/g, ''],
    [/majestuosín/g, ''],
    [/majestuosita/g, ''],
    [/majestuosito/g, ''],
    [/majestuosamente/g, ''],
    [/infinimente/g, ''],
    [/cristalinés/g, ''],
    [/inusitamente/g, ''],
    [/asombrosantemente/g, ''],
    [/inmaculadísimas/g, ''],
    [/inmaculante/g, ''],
    [/inmacularamente/g, ''],
    [/\bde de\b/gi, 'de'],
    [/\btu tu\b/gi, 'tu'],
    [/\by y\b/gi, 'y'],
    [/\bla la\b/gi, 'la'],
    [/\bel el\b/gi, 'el'],
    [/\ben en\b/gi, 'en'],
    [/\ba a\b/gi, 'a'],
    [/\bque que\b/gi, 'que'],
    [/\bde la tu\b/gi, 'de tu'],
    [/\btu viejo de pesado diccionario de y papel/gi, 'tu viejo y pesado diccionario de papel'],
    [/\bque de pesaba toneladas en maleta de viaje y\b/gi, 'que pesaba toneladas en tu maleta de viaje'],
    [/\btu persona aplicación\b/gi, 'aplicación'],
    [/\bde tu la\b/gi, 'de la'],
    [/\bde la de la\b/gi, 'de la'],
    [/\bde tu de\b/gi, 'de tu'],
    [/\by de la de\b/gi, 'y de la'],
    [/\btu de tu\b/gi, 'tu'],
    [/\bde la tu\b/gi, 'de tu'],
    [/\bde forma y de\b/gi, 'de forma'],
    [/\bde la manera automática\b/gi, 'de manera automática'],
    [/\bde la forma natural\b/gi, 'de forma natural'],
    [/\bde tu y de la un\b/gi, 'de un'],
    [/\btu y de\b/gi, 'y'],
    [/\bde tu y\b/gi, 'y'],
    [/\ben de tu\b/gi, 'en tu'],
    [/\bde tu\b/gi, 'tu'], // aggressive, "de tu" is mostly spam in this text
    [/\bde la la\b/gi, 'de la'],
    [/\bde el\b/gi, 'del'],
    [/\by de\b/gi, 'y'],
    [/\bde y\b/gi, 'de'],
    [/\by la\b/gi, 'y la'],
    [/\ben la de\b/gi, 'en la'],
    [/\bde forma\b/gi, ''],
    [/\bde manera\b/gi, ''],
    [/\bde tu de la\b/gi, 'de la'],
    [/\bde tu y\b/gi, 'y'],
    [/\bde la tu vida\b/gi, 'de tu vida'],
    [/\ben la tu\b/gi, 'en tu'],
    [/\bde la tu pantalla\b/gi, 'de tu pantalla'],
    [/\btu de la\b/gi, 'de la'],
    [/\bde la el\b/gi, 'el'],
    [/\by de la un\b/gi, 'y un'],
    [/\bde la tu\b/gi, 'tu'],
    [/\bde grande\b/gi, ''],
    [/\bde grandes\b/gi, ''],
    [/\btu persona\b/gi, ''],
    [/\btu y\b/gi, 'y'],
    [/\by tu\b/gi, 'y'],
    [/\btu de\b/gi, 'de'],
    [/\bde la tu\b/gi, 'de tu'],
    [/\ben tu de\b/gi, 'en tu'],
    [/\bde tu tu\b/gi, 'de tu'],
    [/\bde la la\b/gi, 'de la'],
    [/\ben la la\b/gi, 'en la'],
    [/\bde la de\b/gi, 'de'],
    [/\bde un de\b/gi, 'de un'],
    [/\bde una de\b/gi, 'de una'],
    [/\ben un de\b/gi, 'en un'],
    [/\ben una de\b/gi, 'en una'],
    [/\bde los de\b/gi, 'de los'],
    [/\bde las de\b/gi, 'de las'],
    [/\bde sus de\b/gi, 'de sus'],
    [/\bde su de\b/gi, 'de su'],
    [/\ba la de\b/gi, 'a la'],
    [/\ba el de\b/gi, 'al'],
    [/\ba los de\b/gi, 'a los'],
    [/\ba las de\b/gi, 'a las'],
    [/\bcon la de\b/gi, 'con la'],
    [/\bcon el de\b/gi, 'con el'],
    [/\bpor la de\b/gi, 'por la'],
    [/\bpor el de\b/gi, 'por el'],
    [/\bpara la de\b/gi, 'para la'],
    [/\bpara el de\b/gi, 'para el'],
    [/\bque la de\b/gi, 'que la'],
    [/\bque el de\b/gi, 'que el'],
    [/\bcomo la de\b/gi, 'como la'],
    [/\bcomo el de\b/gi, 'como el'],
    [/\bo la de\b/gi, 'o la'],
    [/\bo el de\b/gi, 'o el'],
    [/\bu la de\b/gi, 'u la'],
    [/\bu el de\b/gi, 'u el'],
    [/\bni la de\b/gi, 'ni la'],
    [/\bni el de\b/gi, 'ni el'],
    [/\bsin la de\b/gi, 'sin la'],
    [/\bsin el de\b/gi, 'sin el'],
    [/\bsobre la de\b/gi, 'sobre la'],
    [/\bsobre el de\b/gi, 'sobre el'],
    [/\btras la de\b/gi, 'tras la'],
    [/\btras el de\b/gi, 'tras el'],
    [/\bante la de\b/gi, 'ante la'],
    [/\bante el de\b/gi, 'ante el'],
    [/\bbajo la de\b/gi, 'bajo la'],
    [/\bbajo el de\b/gi, 'bajo el'],
    [/\bcabe la de\b/gi, 'cabe la'],
    [/\bcabe el de\b/gi, 'cabe el'],
    [/\bdesde la de\b/gi, 'desde la'],
    [/\bdesde el de\b/gi, 'desde el'],
    [/\bhacia la de\b/gi, 'hacia la'],
    [/\bhacia el de\b/gi, 'hacia el'],
    [/\bhasta la de\b/gi, 'hasta la'],
    [/\bhasta el de\b/gi, 'hasta el'],
    [/\bmediante la de\b/gi, 'mediante la'],
    [/\bmediante el de\b/gi, 'mediante el'],
    [/\bpara con la de\b/gi, 'para con la'],
    [/\bpara con el de\b/gi, 'para con el'],
    [/\bsegún la de\b/gi, 'según la'],
    [/\bsegún el de\b/gi, 'según el'],
    [/\bso la de\b/gi, 'so la'],
    [/\bso el de\b/gi, 'so el'],
    [/\bversus la de\b/gi, 'versus la'],
    [/\bversus el de\b/gi, 'versus el'],
    [/\bvia la de\b/gi, 'via la'],
    [/\bvia el de\b/gi, 'via el'],
    [/\bde de\b/gi, 'de'],
    [/\bla la\b/gi, 'la'],
    [/\bel el\b/gi, 'el'],
    [/\by y\b/gi, 'y'],
    [/\bque que\b/gi, 'que'],
    [/\bcon con\b/gi, 'con'],
    [/\bpor por\b/gi, 'por'],
    [/\bpara para\b/gi, 'para'],
    [/\bcomo como\b/gi, 'como'],
    [/\bo o\b/gi, 'o'],
    [/\bu u\b/gi, 'u'],
    [/\bni ni\b/gi, 'ni'],
    [/\bsin sin\b/gi, 'sin'],
    [/\bsobre sobre\b/gi, 'sobre'],
    [/\btras tras\b/gi, 'tras'],
    [/\bante ante\b/gi, 'ante'],
    [/\bbajo bajo\b/gi, 'bajo'],
    [/\bcabe cabe\b/gi, 'cabe'],
    [/\bdesde desde\b/gi, 'desde'],
    [/\bhacia hacia\b/gi, 'hacia'],
    [/\bhasta hasta\b/gi, 'hasta'],
    [/\bmediante mediante\b/gi, 'mediante'],
    [/\bsegún según\b/gi, 'según'],
    [/\bso so\b/gi, 'so'],
    [/\bversus versus\b/gi, 'versus'],
    [/\bvia via\b/gi, 'via'],
    [/\bde la de\b/gi, 'de la'],
    [/\ben la de\b/gi, 'en la'],
    [/\bde la la\b/gi, 'de la'],
    [/\ba la la\b/gi, 'a la'],
    [/\ben la la\b/gi, 'en la'],
    [/\bcon la la\b/gi, 'con la'],
    [/\bpor la la\b/gi, 'por la'],
    [/\bpara la la\b/gi, 'para la'],
    [/\bde el el\b/gi, 'del'],
    [/\ba el el\b/gi, 'al'],
    [/\ben el el\b/gi, 'en el'],
    [/\bcon el el\b/gi, 'con el'],
    [/\bpor el el\b/gi, 'por el'],
    [/\bpara el el\b/gi, 'para el'],
    [/\bde la el\b/gi, 'del'],
    [/\ben la el\b/gi, 'en el'],
    [/\ba la el\b/gi, 'al'],
    [/\bcon la el\b/gi, 'con el'],
    [/\bpor la el\b/gi, 'por el'],
    [/\bpara la el\b/gi, 'para el'],
    [/\bde el la\b/gi, 'de la'],
    [/\ba el la\b/gi, 'a la'],
    [/\ben el la\b/gi, 'en la'],
    [/\bcon el la\b/gi, 'con la'],
    [/\bpor el la\b/gi, 'por la'],
    [/\bpara el la\b/gi, 'para la'],
    [/\bde los los\b/gi, 'de los'],
    [/\ba los los\b/gi, 'a los'],
    [/\ben los los\b/gi, 'en los'],
    [/\bcon los los\b/gi, 'con los'],
    [/\bpor los los\b/gi, 'por los'],
    [/\bpara los los\b/gi, 'para los'],
    [/\bde las las\b/gi, 'de las'],
    [/\ba las las\b/gi, 'a las'],
    [/\ben las las\b/gi, 'en las'],
    [/\bcon las las\b/gi, 'con las'],
    [/\bpor las las\b/gi, 'por las'],
    [/\bpara las las\b/gi, 'para las'],
    [/\bde un un\b/gi, 'de un'],
    [/\ba un un\b/gi, 'a un'],
    [/\ben un un\b/gi, 'en un'],
    [/\bcon un un\b/gi, 'con un'],
    [/\bpor un un\b/gi, 'por un'],
    [/\bpara un un\b/gi, 'para un'],
    [/\bde una una\b/gi, 'de una'],
    [/\ba una una\b/gi, 'a una'],
    [/\ben una una\b/gi, 'en una'],
    [/\bcon una una\b/gi, 'con una'],
    [/\bpor una una\b/gi, 'por una'],
    [/\bpara una una\b/gi, 'para una'],
    [/\bde unos unos\b/gi, 'de unos'],
    [/\ba unos unos\b/gi, 'a unos'],
    [/\ben unos unos\b/gi, 'en unos'],
    [/\bcon unos unos\b/gi, 'con unos'],
    [/\bpor unos unos\b/gi, 'por unos'],
    [/\bpara unos unos\b/gi, 'para unos'],
    [/\bde unas unas\b/gi, 'de unas'],
    [/\ba unas unas\b/gi, 'a unas'],
    [/\ben unas unas\b/gi, 'en unas'],
    [/\bcon unas unas\b/gi, 'con unas'],
    [/\bpor unas unas\b/gi, 'por unas'],
    [/\bpara unas unas\b/gi, 'para unas'],
    [/\bde este este\b/gi, 'de este'],
    [/\ba este este\b/gi, 'a este'],
    [/\ben este este\b/gi, 'en este'],
    [/\bcon este este\b/gi, 'con este'],
    [/\bpor este este\b/gi, 'por este'],
    [/\bpara este este\b/gi, 'para este'],
    [/\bde esta esta\b/gi, 'de esta'],
    [/\ba esta esta\b/gi, 'a esta'],
    [/\ben esta esta\b/gi, 'en esta'],
    [/\bcon esta esta\b/gi, 'con esta'],
    [/\bpor esta esta\b/gi, 'por esta'],
    [/\bpara esta esta\b/gi, 'para esta'],
    [/\bde estos estos\b/gi, 'de estos'],
    [/\ba estos estos\b/gi, 'a estos'],
    [/\ben estos estos\b/gi, 'en estos'],
    [/\bcon estos estos\b/gi, 'con estos'],
    [/\bpor estos estos\b/gi, 'por estos'],
    [/\bpara estos estos\b/gi, 'para estos'],
    [/\bde estas estas\b/gi, 'de estas'],
    [/\ba estas estas\b/gi, 'a estas'],
    [/\ben estas estas\b/gi, 'en estas'],
    [/\bcon estas estas\b/gi, 'con estas'],
    [/\bpor estas estas\b/gi, 'por estas'],
    [/\bpara estas estas\b/gi, 'para estas'],
    [/\bde ese ese\b/gi, 'de ese'],
    [/\ba ese ese\b/gi, 'a ese'],
    [/\ben ese ese\b/gi, 'en ese'],
    [/\bcon ese ese\b/gi, 'con ese'],
    [/\bpor ese ese\b/gi, 'por ese'],
    [/\bpara ese ese\b/gi, 'para ese'],
    [/\bde esa esa\b/gi, 'de esa'],
    [/\ba esa esa\b/gi, 'a esa'],
    [/\ben esa esa\b/gi, 'en esa'],
    [/\bcon esa esa\b/gi, 'con esa'],
    [/\bpor esa esa\b/gi, 'por esa'],
    [/\bpara esa esa\b/gi, 'para esa'],
    [/\bde esos esos\b/gi, 'de esos'],
    [/\ba esos esos\b/gi, 'a esos'],
    [/\ben esos esos\b/gi, 'en esos'],
    [/\bcon esos esos\b/gi, 'con esos'],
    [/\bpor esos esos\b/gi, 'por esos'],
    [/\bpara esos esos\b/gi, 'para esos'],
    [/\bde esas esas\b/gi, 'de esas'],
    [/\ba esas esas\b/gi, 'a esas'],
    [/\ben esas esas\b/gi, 'en esas'],
    [/\bcon esas esas\b/gi, 'con esas'],
    [/\bpor esas esas\b/gi, 'por esas'],
    [/\bpara esas esas\b/gi, 'para esas'],
    [/\bde aquel aquel\b/gi, 'de aquel'],
    [/\ba aquel aquel\b/gi, 'a aquel'],
    [/\ben aquel aquel\b/gi, 'en aquel'],
    [/\bcon aquel aquel\b/gi, 'con aquel'],
    [/\bpor aquel aquel\b/gi, 'por aquel'],
    [/\bpara aquel aquel\b/gi, 'para aquel'],
    [/\bde aquella aquella\b/gi, 'de aquella'],
    [/\ba aquella aquella\b/gi, 'a aquella'],
    [/\ben aquella aquella\b/gi, 'en aquella'],
    [/\bcon aquella aquella\b/gi, 'con aquella'],
    [/\bpor aquella aquella\b/gi, 'por aquella'],
    [/\bpara aquella aquella\b/gi, 'para aquella'],
    [/\bde aquellos aquellos\b/gi, 'de aquellos'],
    [/\ba aquellos aquellos\b/gi, 'a aquellos'],
    [/\ben aquellos aquellos\b/gi, 'en aquellos'],
    [/\bcon aquellos aquellos\b/gi, 'con aquellos'],
    [/\bpor aquellos aquellos\b/gi, 'por aquellos'],
    [/\bpara aquellos aquellos\b/gi, 'para aquellos'],
    [/\bde aquellas aquellas\b/gi, 'de aquellas'],
    [/\ba aquellas aquellas\b/gi, 'a aquellas'],
    [/\ben aquellas aquellas\b/gi, 'en aquellas'],
    [/\bcon aquellas aquellas\b/gi, 'con aquellas'],
    [/\bpor aquellas aquellas\b/gi, 'por aquellas'],
    [/\bpara aquellas aquellas\b/gi, 'para aquellas'],
    [/\bde mi mi\b/gi, 'de mi'],
    [/\ba mi mi\b/gi, 'a mi'],
    [/\ben mi mi\b/gi, 'en mi'],
    [/\bcon mi mi\b/gi, 'con mi'],
    [/\bpor mi mi\b/gi, 'por mi'],
    [/\bpara mi mi\b/gi, 'para mi'],
    [/\bde tu tu\b/gi, 'de tu'],
    [/\ba tu tu\b/gi, 'a tu'],
    [/\ben tu tu\b/gi, 'en tu'],
    [/\bcon tu tu\b/gi, 'con tu'],
    [/\bpor tu tu\b/gi, 'por tu'],
    [/\bpara tu tu\b/gi, 'para tu'],
    [/\bde su su\b/gi, 'de su'],
    [/\ba su su\b/gi, 'a su'],
    [/\ben su su\b/gi, 'en su'],
    [/\bcon su su\b/gi, 'con su'],
    [/\bpor su su\b/gi, 'por su'],
    [/\bpara su su\b/gi, 'para su'],
    [/\bde nuestro nuestro\b/gi, 'de nuestro'],
    [/\ba nuestro nuestro\b/gi, 'a nuestro'],
    [/\ben nuestro nuestro\b/gi, 'en nuestro'],
    [/\bcon nuestro nuestro\b/gi, 'con nuestro'],
    [/\bpor nuestro nuestro\b/gi, 'por nuestro'],
    [/\bpara nuestro nuestro\b/gi, 'para nuestro'],
    [/\bde nuestra nuestra\b/gi, 'de nuestra'],
    [/\ba nuestra nuestra\b/gi, 'a nuestra'],
    [/\ben nuestra nuestra\b/gi, 'en nuestra'],
    [/\bcon nuestra nuestra\b/gi, 'con nuestra'],
    [/\bpor nuestra nuestra\b/gi, 'por nuestra'],
    [/\bpara nuestra nuestra\b/gi, 'para nuestra'],
    [/\bde nuestros nuestros\b/gi, 'de nuestros'],
    [/\ba nuestros nuestros\b/gi, 'a nuestros'],
    [/\ben nuestros nuestros\b/gi, 'en nuestros'],
    [/\bcon nuestros nuestros\b/gi, 'con nuestros'],
    [/\bpor nuestros nuestros\b/gi, 'por nuestros'],
    [/\bpara nuestros nuestros\b/gi, 'para nuestros'],
    [/\bde nuestras nuestras\b/gi, 'de nuestras'],
    [/\ba nuestras nuestras\b/gi, 'a nuestras'],
    [/\ben nuestras nuestras\b/gi, 'en nuestras'],
    [/\bcon nuestras nuestras\b/gi, 'con nuestras'],
    [/\bpor nuestras nuestras\b/gi, 'por nuestras'],
    [/\bpara nuestras nuestras\b/gi, 'para nuestras'],
    [/\bde vuestro vuestro\b/gi, 'de vuestro'],
    [/\ba vuestro vuestro\b/gi, 'a vuestro'],
    [/\ben vuestro vuestro\b/gi, 'en vuestro'],
    [/\bcon vuestro vuestro\b/gi, 'con vuestro'],
    [/\bpor vuestro vuestro\b/gi, 'por vuestro'],
    [/\bpara vuestro vuestro\b/gi, 'para vuestro'],
    [/\bde vuestra vuestra\b/gi, 'de vuestra'],
    [/\ba vuestra vuestra\b/gi, 'a vuestra'],
    [/\ben vuestra vuestra\b/gi, 'en vuestra'],
    [/\bcon vuestra vuestra\b/gi, 'con vuestra'],
    [/\bpor vuestra vuestra\b/gi, 'por vuestra'],
    [/\bpara vuestra vuestra\b/gi, 'para vuestra'],
    [/\bde vuestros vuestros\b/gi, 'de vuestros'],
    [/\ba vuestros vuestros\b/gi, 'a vuestros'],
    [/\ben vuestros vuestros\b/gi, 'en vuestros'],
    [/\bcon vuestros vuestros\b/gi, 'con vuestros'],
    [/\bpor vuestros vuestros\b/gi, 'por vuestros'],
    [/\bpara vuestros vuestros\b/gi, 'para vuestros'],
    [/\bde vuestras vuestras\b/gi, 'de vuestras'],
    [/\ba vuestras vuestras\b/gi, 'a vuestras'],
    [/\ben vuestras vuestras\b/gi, 'en vuestras'],
    [/\bcon vuestras vuestras\b/gi, 'con vuestras'],
    [/\bpor vuestras vuestras\b/gi, 'por vuestras'],
    [/\bpara vuestras vuestras\b/gi, 'para vuestras'],
    [/\bde y\b/gi, 'de'],
    [/\by de\b/gi, 'y'],
    [/\bo de\b/gi, 'o'],
    [/\bde o\b/gi, 'o'],
    [/\bu de\b/gi, 'u'],
    [/\bde u\b/gi, 'u'],
    [/\bni de\b/gi, 'ni'],
    [/\bde ni\b/gi, 'ni'],
    [/\bque de\b/gi, 'que'],
    [/\bde que\b/gi, 'de que'],
    [/\bcomo de\b/gi, 'como'],
    [/\bde como\b/gi, 'de como'],
    [/\bpero de\b/gi, 'pero'],
    [/\bde pero\b/gi, 'de pero'],
    [/\baunque de\b/gi, 'aunque'],
    [/\bde aunque\b/gi, 'de aunque'],
    [/\bsino de\b/gi, 'sino'],
    [/\bde sino\b/gi, 'de sino'],
    [/\bmás de\b/gi, 'más de'],
    [/\bde más\b/gi, 'de más'],
    [/\bmenos de\b/gi, 'menos de'],
    [/\bde menos\b/gi, 'de menos'],
    [/\bmuy de\b/gi, 'muy'],
    [/\bde muy\b/gi, 'de muy'],
    [/\bde de\b/gi, 'de'],
    [/\b  +/g, ' '],
    [/ ,/g, ','],
    [/ \./g, '.'],
    [/ \)/g, ')'],
    [/\( /g, '('],
    [/ :/g, ':'],
    [/ ;/g, ';'],
    [/ \?/g, '?'],
    [/ \!/g, '!'],
    [/\¿ /g, '¿'],
    [/\¡ /g, '¡'],
  ];

  for (const [regex, replacement] of replacements) {
    content = content.replace(regex, replacement);
  }
  
  // Double pass to fix any new adjacent duplicates created by the first pass
  content = content.replace(/\b(de|la|el|tu|y|a|en)\s+\1\b/gi, '$1');
  content = content.replace(/\bde la de\b/gi, 'de la');
  content = content.replace(/\bde el de\b/gi, 'del');
  content = content.replace(/\ben la de\b/gi, 'en la');
  content = content.replace(/\by de\b/gi, 'y');
  content = content.replace(/\bde y\b/gi, 'y');

  // Specific cleanups observed:
  content = content.replace(/de tu/gi, 'tu');
  content = content.replace(/y tu/gi, 'y');
  content = content.replace(/de la/gi, 'la');
  content = content.replace(/la la/gi, 'la');
  content = content.replace(/tu tu/gi, 'tu');

  fs.writeFileSync(articlesPath, content, 'utf-8');
  console.log('Deep cleaned articles.ts');
}
