export const tools = [
    {
        id: 'claude_opus_4_6',
        name: 'Claude Opus 4.6',
        sector: 'Chatbots y Asistentes',
        logo: 'claude',
        emoji: '🧠',
        isFullyFree: false,
        freeTierDetails: 'De pago',
        url: 'https://claude.ai',
        description: 'La versión más avanzada y capaz de Claude para tareas complejas.',
        longDescription: 'Claude Opus 4.6 es la inteligencia artificial líder de Anthropic para realizar análisis complejos, tareas de razonamiento profundo y programación avanzada.'
    },
    {
        id: 'kat_coder_pro_v1',
        name: 'KAT-Coder-pro V1',
        sector: 'Programación',
        logo: 'katcoder',
        emoji: '👨‍💻',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://katcoder.ai',
        description: 'Asistente de programación especializado en generar código libre de errores.',
        longDescription: 'KAT-Coder-pro V1 es una herramienta innovadora para desarrolladores que acelera el ciclo de desarrollo generando, analizando y optimizando código avanzado.'
    },
    {
        id: 'gemini_3_flash',
        name: 'Gemini 3 Flash',
        sector: 'Chatbots y Asistentes',
        logo: 'gemini',
        emoji: '⚡',
        isFullyFree: true,
        freeTierDetails: 'Gratis',
        url: 'https://gemini.google.com',
        description: 'Modelo ultrarrápido de Google diseñado para respuestas inmediatas.',
        longDescription: 'Gemini 3 Flash es la solución perfecta para tareas de inferencia de baja latencia y alta frecuencia, manteniendo una gran capacidad de razonamiento con tiempos de respuesta sorprendentes.'
    },
    {
        id: 'claude_sonnet_4_6',
        name: 'Claude Sonnet 4.6',
        sector: 'Chatbots y Asistentes',
        logo: 'claude',
        emoji: '🤖',
        isFullyFree: true,
        freeTierDetails: 'Freemium',
        url: 'https://claude.ai',
        description: 'El equilibrio perfecto entre inteligencia y velocidad de Anthropic.',
        longDescription: 'Claude Sonnet 4.6 destaca por su eficiencia superior para tareas empresariales del día a día, ofreciendo resultados rápidos sin sacrificar comprensión u elocuencia.'
    },
    {
        id: 'kimi_k2_5',
        name: 'Kimi K2.5',
        sector: 'Investigación y Datos',
        logo: 'kimi',
        emoji: '📚',
        isFullyFree: true,
        freeTierDetails: 'Gratis',
        url: 'https://kimi.moonshot.cn',
        description: 'IA especializada en procesamiento de documentos largos en profundidad.',
        longDescription: 'Kimi K2.5 permite cargar y analizar documentos extremadamente largos y complejos, siendo la herramienta predilecta para investigadores y estudiantes que necesitan resumir textos densos.'
    },
    {
        id: 'claude_haiku_4_5',
        name: 'Claude Haiku 4.5',
        sector: 'Chatbots y Asistentes',
        logo: 'claude',
        emoji: '💨',
        isFullyFree: true,
        freeTierDetails: 'Gratis',
        url: 'https://claude.ai',
        description: 'El modelo más rápido y accesible de la familia Claude.',
        longDescription: 'Claude Haiku 4.5 es ideal para interacciones conversacionales ágiles y tareas simples que requieren respuestas casi instantáneas con la seguridad que caracteriza a Anthropic.'
    },
    {
        id: 'gemini_2_5_flash',
        name: 'Gemini 2.5 Flash',
        sector: 'Chatbots y Asistentes',
        logo: 'gemini',
        emoji: '🌟',
        isFullyFree: true,
        freeTierDetails: 'Gratis',
        url: 'https://gemini.google.com',
        description: 'Eficiencia y rendimiento superior en procesamiento multimodal veloz.',
        longDescription: 'Gemini 2.5 Flash incorpora mejoras significativas en velocidad para manejar entradas multimodales (texto, audio y video) de forma rápida y costo-eficiente en Google Cloud y la interfaz web.'
    },
    {
        id: 'minimax_m2_5',
        name: 'MiniMax M2.5',
        sector: 'Chatbots y Asistentes',
        logo: 'minimax',
        emoji: '🎭',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://minimax.info',
        description: 'Modelo de lenguaje innovador con gran capacidad de role-play.',
        longDescription: 'MiniMax M2.5 es líder en la generación de diálogos humanizados y creatividad, destacando enormemente en la creación de personajes interactivos y entretenimiento conversacional.'
    },
    {
        id: 'claude_3_7_sonnet',
        name: 'Claude 3.7 Sonnet',
        sector: 'Chatbots y Asistentes',
        logo: 'claude',
        emoji: '🧠',
        isFullyFree: true,
        freeTierDetails: 'Freemium',
        url: 'https://claude.ai',
        description: 'Modelo clave en la evolución de inteligencia artificial de Anthropic.',
        longDescription: 'Claude 3.7 Sonnet combina asombrosas capacidades de codificación con redacción experta, marcando un potente hito evolutivo en la familia Claude.'
    },
    {
        id: 'gpt_5_2',
        name: 'GPT 5.2',
        sector: 'Chatbots y Asistentes',
        logo: 'chatgpt',
        emoji: '🚀',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://chatgpt.com',
        description: 'El pionero indiscutible evoluciona hacia una inteligencia revolucionaria.',
        longDescription: 'GPT 5.2 empuja los límites del entendimiento del lenguaje natural, razonamiento lógico y aplicaciones multimodales para brindar una experiencia de asistencia sin precedentes en la industria.'
    },
    {
        id: 'claude',
        name: 'Claude 3.5 Sonnet',
        sector: 'Escritura y Productividad',
        logo: 'claude',
        emoji: '🤖',
        isFullyFree: true,
        freeTierDetails: '100% Gratis',
        url: 'https://claude.ai',
        description: 'La inteligencia artificial más avanzada para redacción natural y análisis de textos.',
        longDescription: 'Ofrece la redacción más humana y coherente del mercado sin costo. Ideal para ensayos, correos, y cualquier tipo de redacción profesional. Destaca por su capacidad para seguir instrucciones de formato y su tono natural, superando a menudo a alternativas de pago en la calidad pura del texto producido.'
    },
    {
        id: 'leonardo',
        name: 'Leonardo.ai',
        sector: 'Imagen y Diseño',
        logo: 'leonardo',
        emoji: '🎨',
        isFullyFree: false,
        freeTierDetails: 'Freemium (150 tokens/día)',
        url: 'https://leonardo.ai',
        description: 'Generación de imágenes espectaculares con calidad profesional. El mejor freemium.',
        longDescription: 'Da 150 tokens diarios gratis. Es mejor que Midjourney si no quieres pagar, permitiendo crear arte profesional. La plataforma incluye multitud de modelos afinados (\'finetuned\'), creación de texturas 3D y edición asistida por IA para mantener la consistencia en los personajes o estilos.'
    },
    {
        id: 'deepseek',
        name: 'DeepSeek R1',
        sector: 'Programación',
        logo: 'deepseek',
        emoji: '🐳',
        isFullyFree: true,
        freeTierDetails: 'Open Source',
        url: 'https://chat.deepseek.com',
        description: 'Potente modelo para resolver problemas lógicos y programar. Alta eficiencia.',
        longDescription: 'Una IA de código abierto potentísima. Supera a muchos modelos de pago en razonamiento lógico y programación. Ofrece sugerencias de código súper precisas, un análisis de repositorio avanzado y una ventana de contexto amplia para leer bases de código extensas.'
    },
    {
        id: 'perplexity',
        name: 'Perplexity AI',
        sector: 'Investigación y Datos',
        logo: 'perplexity',
        emoji: '🔍',
        isFullyFree: false,
        freeTierDetails: 'Búsqueda Gratis',
        url: 'https://www.perplexity.ai',
        description: 'El mejor buscador conversacional actual con fuentes en tiempo real.',
        longDescription: 'Sustituye a Google. Te da respuestas con fuentes citadas en tiempo real, ideal para estudiantes y periodistas. Combina un potente motor de búsqueda con los mejores LLMs para sintetizar la información de múltiples webs y darte una respuesta estructurada libre de publicidad.'
    },
    {
        id: 'gamma',
        name: 'Gamma App',
        sector: 'Escritura y Productividad',
        logo: 'gamma',
        emoji: '🪄',
        isFullyFree: false,
        freeTierDetails: 'Freemium (Créditos iniciales)',
        url: 'https://gamma.app',
        description: 'Genera presentaciones completas y documentos estéticos con solo un prompt.',
        longDescription: 'Crea presentaciones enteras (diapositivas) con un solo prompt. Te ahorra horas de diseño en PowerPoint. Su interfaz es ultra-fluida y te permite ajustar cada diapositiva de forma interactiva e iterativa. Ideal para presentar propuestas a clientes rápidamente.'
    },
    {
        id: 'capcut',
        name: 'CapCut Desktop IA',
        sector: 'Video y Animación',
        logo: 'capcut',
        emoji: '✂️',
        isFullyFree: false,
        freeTierDetails: 'Funciones Gratis',
        url: 'https://www.capcut.com',
        description: 'El editor de video favorito ahora con subtítulos automáticos y más IA.',
        longDescription: 'Incluye funciones de subtitulado automático y edición por IA totalmente gratuitas y fáciles de usar. Remueve fondos sin chroma key, mejora el audio aislando la voz y genera subtítulos dinámicos que retienen la atención en RRSS (TikTok, Reels, Shorts).'
    },
    {
        id: 'copilot',
        name: 'Microsoft Copilot',
        sector: 'Escritura y Productividad',
        logo: 'copilot',
        emoji: '✈️',
        isFullyFree: true,
        freeTierDetails: '100% Gratis',
        url: 'https://copilot.microsoft.com',
        description: 'Asistente de IA integral que utiliza GPT-4 y DALL-E gratis.',
        longDescription: 'Integrado en el ecosistema de Microsoft, Copilot ofrece acceso gratuito a modelos de lenguaje avanzados (GPT-4) y generadores de imágenes (DALL-E 3) con acceso a internet en tiempo real. Es tu mejor aliado para buscar, resumir y crear en el día a día sin pagar suscripciones.'
    },
    {
        id: 'cursor',
        name: 'Cursor AI',
        sector: 'Programación',
        logo: 'cursor',
        emoji: '🖱️',
        isFullyFree: false,
        freeTierDetails: 'Freemium (Plan Básico)',
        url: 'https://www.cursor.com',
        description: 'El editor de código moderno con IA nativa y refactorización inteligente.',
        longDescription: 'Construido sobre VS Code, incluye funciones avanzadas de autocompletado y chat con IA basándose en todo el contexto de tu proyecto. Su plan gratuito ofrece una cantidad generosa de peticiones a modelos avanzados, ideal para desarrollar mucho más rápido con asistencia premium.'
    },
    {
        id: 'suno',
        name: 'Suno AI',
        sector: 'Audio y Música',
        logo: 'suno',
        emoji: '🎵',
        isFullyFree: false,
        freeTierDetails: '50 Créditos Diarios',
        url: 'https://suno.com',
        description: 'Genera canciones completas con voces y bases musicales ultra-realistas.',
        longDescription: 'Suno revoluciona la creación de audio, permitiendo a cualquier persona componer canciones completas (letra, música y cantantes) especificando solo el género y la temática. El tier gratuito te da créditos suficientes para crear varios temas creativos cada día.'
    },
    {
        id: 'flux',
        name: 'Flux.1 (via Fal)',
        sector: 'Imagen y Diseño',
        logo: 'flux',
        emoji: '🌌',
        isFullyFree: true,
        freeTierDetails: 'Versiones de acceso abierto',
        url: 'https://fal.ai/models/fal-ai/flux/schnell',
        description: 'El generador de imágenes de mayor calidad en Open Source actual.',
        longDescription: 'Creado por los cerebros detrás de Stable Diffusion, Flux.1 proporciona una anatomía hiperrealista y entiende el texto de los prompts mejor que casi cualquier otra IA. Accesible a través de múltiples hubs gratuitos para resultados espectaculares.'
    },
    {
        id: 'chatgpt',
        name: 'ChatGPT',
        sector: 'Escritura y Productividad',
        logo: 'chatgpt',
        emoji: '💬',
        isFullyFree: false,
        freeTierDetails: 'Plan Básico Gratis',
        url: 'https://chatgpt.com',
        description: 'Asistente de IA versátil y potente para cualquier tarea de trabajo diario.',
        longDescription: 'La IA más popular del mundo te permite redactar, resumir correos, generar ideas y organizar tu trabajo. El plan gratuito ahora incluye acceso al modelo GPT-4o mini, suficientemente rápido e inteligente para agilizar casi cualquier tarea de oficina o trabajo en equipo.'
    },
    {
        id: 'cody',
        name: 'Cody (Sourcegraph)',
        sector: 'Programación',
        logo: 'cody',
        emoji: '👨‍💻',
        isFullyFree: true,
        freeTierDetails: 'Individual Gratis',
        url: 'https://sourcegraph.com/cody',
        description: 'Asistente de código IA que conoce todo tu repositorio de trabajo.',
        longDescription: 'A diferencia de otros autocompletados limitados, Cody lee todo tu código para escribir y corregir funciones basándose en el contexto general de tu arquitectura de software. Es el compañero perfecto para la programación e informática, y su plan personal es 100% gratis.'
    },
    {
        id: 'udio',
        name: 'Udio AI',
        sector: 'Audio y Música',
        logo: 'udio',
        emoji: '🎧',
        isFullyFree: false,
        freeTierDetails: 'Freemium (Créditos Diarios)',
        url: 'https://www.udio.com',
        description: 'Crea música de altísima calidad y nitidez profesional al instante.',
        longDescription: 'Udio es espectacular para crear canciones, bases de rap, música épica para juegos o jingles. A diferencia de otros, la calidad y separación de instrumentos es casi indistinguible del audio de estudio real. Genial para la producción musical y exploración creativa de cualquier género.'
    },
    {
        id: 'chefgpt',
        name: 'ChefGPT',
        sector: 'Cocina',
        logo: 'chefgpt',
        emoji: '👨‍🍳',
        isFullyFree: false,
        freeTierDetails: 'Plan Básico Gratis',
        url: 'https://www.chefgpt.com',
        description: 'Tu chef personal de IA. Recetas a partir de lo que hay en tu nevera.',
        longDescription: 'Ideal para la cocina diaria. Simplemente le dices a la IA qué ingredientes te sobran en la despensa, tus objetivos macro nutricionales o alergias, y te generará recetas saludables paso a paso para cocinar sin desperdiciar comida. Elimina la eterna pregunta de "¿qué ceno hoy?".'
    },
    {
        id: 'julius',
        name: 'Julius AI',
        sector: 'Investigación y Datos',
        logo: 'julius',
        emoji: '📊',
        isFullyFree: false,
        freeTierDetails: 'Freemium (Análisis Básico)',
        url: 'https://julius.ai',
        description: 'Analista de datos que procesa Excels, CSVs y dibuja gráficos avanzados.',
        longDescription: 'Julius es tu científico de datos personal. Sube un archivo Excel, CSV o conecta tu base de datos y pídele en lenguaje natural que encuentre tendencias, haga previsiones o grafique tus ventas. Perfecto para analistas sin conocimientos profundos de programación en Python analítico.'
    },
    {
        id: 'notebooklm',
        name: 'NotebookLM (Google)',
        sector: 'Investigación y Datos',
        logo: 'notebooklm',
        emoji: '📓',
        isFullyFree: true,
        freeTierDetails: '100% Gratis',
        url: 'https://notebooklm.google.com',
        description: 'Convierte tus apuntes en podcasts interactivos y guías de estudio.',
        longDescription: 'La revolución para estudiantes. Sube tus PDFs, apuntes de clase o enlaces de YouTube, y NotebookLM te creará resúmenes, tests de repaso, e incluso un podcast donde dos presentadores de IA debaten y explican tus apuntes de forma súper amena.'
    },
    {
        id: 'reclaim',
        name: 'Reclaim AI',
        sector: 'Horarios',
        logo: 'reclaim',
        emoji: '📅',
        isFullyFree: false,
        freeTierDetails: 'Plan Básico Gratis',
        url: 'https://reclaim.ai',
        description: 'Organiza tu calendario agrupando tareas, hábitos y descansos automáticos.',
        longDescription: 'Ideal para gestionar tu tiempo sin estrés. Se sincroniza con Google Calendar y automáticamente encaja tus tareas pendientes en los huecos libres, protegiendo tiempo para ti, tus hábitos (ej. "Ir al gimnasio") y reprogramando todo automáticamente si surge una urgencia.'
    },
    {
        id: 'vmake',
        name: 'Vmake AI Fashion',
        sector: 'Moda',
        logo: 'vmake',
        emoji: '👗',
        isFullyFree: false,
        freeTierDetails: 'Freemium (Créditos Gratis)',
        url: 'https://vmake.ai',
        description: 'Pruébate ropa en modelos virtuales o cámbiate de ropa en fotos.',
        longDescription: 'Una herramienta impresionante para moda y e-commerce. Puedes subir la foto de una prenda y Vmake generará modelos realistas de diferentes tallas y etnias luciéndola. También incluye funciones de Virtual Try-On para ver cómo te quedarían a ti los outfits.'
    },
    {
        id: 'quillbot',
        name: 'QuillBot',
        sector: 'Escritura y Productividad',
        logo: 'quillbot',
        emoji: '✍️',
        isFullyFree: false,
        freeTierDetails: 'Freemium (Plan Básico)',
        url: 'https://quillbot.com',
        description: 'El mejor parafraseador y corrector gramatical impulsado por IA.',
        longDescription: 'Perfecto para reescribir textos, mejorar el vocabulario y evitar el plagio. Su versión gratuita te permite parafrasear párrafos cortos en diferentes tonos (formal, fluido, etc.) de manera inmediata y con excelentes resultados en español e inglés.'
    },
    {
        id: 'consensus',
        name: 'Consensus AI',
        sector: 'Investigación y Datos',
        logo: 'consensus',
        emoji: '🔬',
        isFullyFree: false,
        freeTierDetails: 'Búsqueda Gratis',
        url: 'https://consensus.app',
        description: 'Buscador de IA que solo extrae respuestas de artículos científicos reales.',
        longDescription: 'Si estás haciendo una tesis o un trabajo académico, esta herramienta extrae citas y conclusiones directamente de bases de datos de papers científicos (revisados por pares). Dile adiós a las respuestas inventadas y obtén rigor científico gratis.'
    },
    {
        id: 'luma',
        name: 'Luma Dream Machine',
        sector: 'Video y Animación',
        logo: 'luma',
        emoji: '🎥',
        isFullyFree: false,
        freeTierDetails: '30 Generaciones/Mes',
        url: 'https://lumalabs.ai/dream-machine',
        description: 'Genera clips de video hiperrealistas y de alta calidad a partir de texto.',
        longDescription: 'Una IA revolucionaria para crear videos desde cero o animar imágenes estáticas. Con su plan gratuito obtienes suficientes créditos mensuales para renderizar cinemáticas fluidas o assets rápidos para tus proyectos audiovisuales y redes sociales.'
    },
    {
        id: 'dishgen',
        name: 'DishGen',
        sector: 'Cocina',
        logo: 'dishgen',
        emoji: '🥘',
        isFullyFree: true,
        freeTierDetails: 'Gratis con Límites',
        url: 'https://www.dishgen.com',
        description: 'Generador de recetas creativas que aprovecha las sobras de tu nevera.',
        longDescription: 'Escribe los pocos ingredientes que te quedan y DishGen formulará instantáneamente una receta única con el paso a paso exacto, tiempos de cocción y alternativas. Perfecto para salir del paso sin tener que comprar ingredientes extra.'
    },
    {
        id: 'chatcsv',
        name: 'ChatCSV',
        sector: 'Investigación y Datos',
        logo: 'chatcsv',
        emoji: '📈',
        isFullyFree: false,
        freeTierDetails: 'Uso Básico Gratis',
        url: 'https://www.chatcsv.co',
        description: 'Chatea directamente con tus hojas de cálculo y documentos de datos.',
        longDescription: 'Convierte tus archivos CSV tabulares en un asistente inteligente. Hazle preguntas sobre tu tabla como "qué mes vendimos más?" o "filtra los usuarios inactivos", y ChatCSV leerá la información devolviéndote los datos procesados al instante.'
    },
    {
        id: 'socratic',
        name: 'Socratic by Google',
        sector: 'Investigación y Datos',
        logo: 'socratic',
        emoji: '🦉',
        isFullyFree: true,
        freeTierDetails: '100% Gratis',
        url: 'https://socratic.org',
        description: 'Resolución de problemas de matemáticas, física y ciencias con solo una foto.',
        longDescription: 'Toma una foto a ese problema de álgebra o química que no entiendes, y la IA de Socratic lo desgrana explicándote la solución paso por paso con gráficos y conceptos clave. Una app imprescindible y 100% gratuita para estudiantes.'
    },
    {
        id: 'trevor',
        name: 'Trevor AI',
        sector: 'Horarios',
        logo: 'trevor',
        emoji: '⏳',
        isFullyFree: false,
        freeTierDetails: 'Plan Básico Gratis',
        url: 'https://trevorai.com',
        description: 'Planificador de Time-Blocking para aumentar tu tiempo de concentración.',
        longDescription: 'Aplica la famosa técnica del bloque de tiempo (Time-Blocking) asignando horas específicas a cada tarea de tu lista de pendientes en el calendario. Trevor AI calcula tu carga de trabajo y previene el burnout manteniéndote enfocado.'
    },
    {
        id: 'cala',
        name: 'Cala (Fashion AI)',
        sector: 'Moda',
        logo: 'cala',
        emoji: '👚',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://ca.la',
        description: 'Diseño de ropa y generación de colecciones de moda en segundos.',
        longDescription: 'Es el sistema operativo definitivo para que diseñadores y marcas de ropa creen bocetos impulsados por IA. Combina descripciones de prendas y estilos para obtener renders 3D de alta calidad que puedes llevar directos a la producción textil.'
    },
    {
        id: 'gemini',
        name: 'Google Gemini',
        sector: 'Escritura y Productividad',
        logo: 'gemini',
        emoji: '✨',
        isFullyFree: false,
        freeTierDetails: 'Plan Básico Gratis',
        url: 'https://gemini.google.com',
        description: 'La inteligencia artificial multimodal de Google integrada en su ecosistema.',
        longDescription: 'Gemini destaca por su enorme ventana de contexto y su capacidad nativa para entender texto, código, imágenes y vídeos al mismo tiempo. Al estar integrado con Google Workspace (Docs, Gmail, Drive), es ideal para resumir hojas de cálculo o redactar correos en tu día a día.'
    },
    {
        id: 'midjourney',
        name: 'Midjourney',
        sector: 'Imagen y Diseño',
        logo: 'midjourney',
        emoji: '⛵',
        isFullyFree: false,
        freeTierDetails: 'Solo de Pago',
        url: 'https://www.midjourney.com',
        description: 'El rey indiscutible de la generación de imágenes artísticas y fotorrealistas.',
        longDescription: 'Aunque ya no ofrece prueba gratuita constante, Midjourney v6 es el estándar de la industria creativa. Genera desde fotografías ultrarrealistas hasta logotipos y concept art para videojuegos con una fidelidad gráfica inigualable. Se utiliza a través de Discord o su web oficial.'
    },
    {
        id: 'stablediffusion',
        name: 'Stable Diffusion',
        sector: 'Imagen y Diseño',
        logo: 'stablediffusion',
        emoji: '🖼️',
        isFullyFree: true,
        freeTierDetails: 'Open Source',
        url: 'https://stability.ai',
        description: 'El modelo libre más potente para generar imágenes sin censura localmente.',
        longDescription: 'La gran ventaja de Stable Diffusion (especialmente SDXL) es que puedes descargarlo e instalarlo gratis en tu propio PC. Ofrece un control absoluto mediante interfaces como ComfyUI o Automatic1111, permitiéndote entrenar tus propios modelos (LoRAs) sin depender de suscripciones.'
    },
    {
        id: 'runway',
        name: 'Runway Gen-3',
        sector: 'Video y Animación',
        logo: 'runway',
        emoji: '🎬',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://runwayml.com',
        description: 'La plataforma líder en creación creativa y efectos visuales generativos.',
        longDescription: 'Runway está orientado a cineastas y creadores de contenido. Su modelo Gen-3 Alpha produce vídeos de altísima fidelidad temporal y control de cámara milimétrico. Permite funciones avanzadas como Text-to-Video, Image-to-Video y herramientas mágicas de borrado en movimiento.'
    },
    {
        id: 'kling',
        name: 'Kling AI',
        sector: 'Video y Animación',
        logo: 'kling',
        emoji: '🎞️',
        isFullyFree: false,
        freeTierDetails: 'Créditos Diarios',
        url: 'https://klingai.com',
        description: 'Generación de vídeo hiperrealista y simulación física avanzada.',
        longDescription: 'El principal competidor de Sora (OpenAI) accesible al público. Kling destaca por su increíble entendimiento de la física del mundo real: fluidos, reflejos y movimientos corporales complejos son renderizados con una precisión asombrosa. Ofrece varios créditos diarios en su tier gratuito.'
    },
    {
        id: 'mistral_872',
        name: 'Mistral AI',
        sector: 'Chatbots y Asistentes',
        logo: 'mistral',
        emoji: '👽',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.mistral.com',
        description: 'Modelo europeo potente y eficiente (Open Source).',
        longDescription: 'Modelo europeo potente y eficiente (Open Source). Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Chatbots y Asistentes.'
    },
    {
        id: 'llama_3058',
        name: 'Llama 3 (Meta)',
        sector: 'Chatbots y Asistentes',
        logo: 'llama',
        emoji: '💬',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.llama.com',
        description: 'El modelo abierto más usado por desarrolladores.',
        longDescription: 'El modelo abierto más usado por desarrolladores. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Chatbots y Asistentes.'
    },
    {
        id: 'characterai_5581',
        name: 'Character.ai',
        sector: 'Chatbots y Asistentes',
        logo: 'characterai',
        emoji: '🗣️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.characterai.com',
        description: 'Chat con personajes históricos o de ficción.',
        longDescription: 'Chat con personajes históricos o de ficción. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Chatbots y Asistentes.'
    },
    {
        id: 'grok_5525',
        name: 'Grok (xAI)',
        sector: 'Chatbots y Asistentes',
        logo: 'grok',
        emoji: '🤖',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.grok.com',
        description: 'La IA de Elon Musk integrada en X (Twitter).',
        longDescription: 'La IA de Elon Musk integrada en X (Twitter). Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Chatbots y Asistentes.'
    },
    {
        id: 'dalle_5347',
        name: 'DALL-E 3',
        sector: 'Imagen y Diseño',
        logo: 'dalle',
        emoji: '📸',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.dalle.com',
        description: 'Generación de imágenes precisa desde el chat.',
        longDescription: 'Generación de imágenes precisa desde el chat. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'adobe_681',
        name: 'Adobe Firefly',
        sector: 'Imagen y Diseño',
        logo: 'adobe',
        emoji: '🖍️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.adobe.com',
        description: 'Edición y relleno generativo profesional.',
        longDescription: 'Edición y relleno generativo profesional. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'canva_1777',
        name: 'Canva Magic Studio',
        sector: 'Imagen y Diseño',
        logo: 'canva',
        emoji: '🖼️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.canva.com',
        description: 'Diseño gráfico asistido para no diseñadores.',
        longDescription: 'Diseño gráfico asistido para no diseñadores. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'kreaai_3219',
        name: 'Krea.ai',
        sector: 'Imagen y Diseño',
        logo: 'kreaai',
        emoji: '📸',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.kreaai.com',
        description: 'Generación y mejora de imagen en tiempo real.',
        longDescription: 'Generación y mejora de imagen en tiempo real. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'magnific_8492',
        name: 'Magnific AI',
        sector: 'Imagen y Diseño',
        logo: 'magnific',
        emoji: '📸',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.magnific.com',
        description: 'El mejor reescalador (upscaler) de alta definición.',
        longDescription: 'El mejor reescalador (upscaler) de alta definición. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'recraftai_2074',
        name: 'Recraft.ai',
        sector: 'Imagen y Diseño',
        logo: 'recraftai',
        emoji: '📸',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.recraftai.com',
        description: 'Generación de vectores (.svg) e iconos.',
        longDescription: 'Generación de vectores (.svg) e iconos. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'looka_8362',
        name: 'Looka',
        sector: 'Imagen y Diseño',
        logo: 'looka',
        emoji: '✨',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.looka.com',
        description: 'Creación de logos y branding completo.',
        longDescription: 'Creación de logos y branding completo. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'uizard_223',
        name: 'Uizard',
        sector: 'Imagen y Diseño',
        logo: 'uizard',
        emoji: '🎭',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.uizard.com',
        description: 'Convierte bocetos en prototipos de apps.',
        longDescription: 'Convierte bocetos en prototipos de apps. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'framer_2789',
        name: 'Framer AI',
        sector: 'Imagen y Diseño',
        logo: 'framer',
        emoji: '🖼️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.framer.com',
        description: 'Generación de sitios web completos desde texto.',
        longDescription: 'Generación de sitios web completos desde texto. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'relume_1767',
        name: 'Relume',
        sector: 'Imagen y Diseño',
        logo: 'relume',
        emoji: '🌈',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.relume.com',
        description: 'Estructura y sitemap de webs mediante IA.',
        longDescription: 'Estructura y sitemap de webs mediante IA. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Imagen y Diseño.'
    },
    {
        id: 'heygen_4644',
        name: 'HeyGen',
        sector: 'Video y Animación',
        logo: 'heygen',
        emoji: '🎬',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.heygen.com',
        description: 'Avatares que hablan y traducción de video con lip-sync.',
        longDescription: 'Avatares que hablan y traducción de video con lip-sync. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Video y Animación.'
    },
    {
        id: 'sora_8370',
        name: 'Sora (OpenAI)',
        sector: 'Video y Animación',
        logo: 'sora',
        emoji: '📺',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.sora.com',
        description: 'Video cinemático de alta duración (en despliegue).',
        longDescription: 'Video cinemático de alta duración (en despliegue). Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Video y Animación.'
    },
    {
        id: 'pika_7068',
        name: 'Pika Labs',
        sector: 'Video y Animación',
        logo: 'pika',
        emoji: '📼',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.pika.com',
        description: 'Animaciones y efectos visuales creativos.',
        longDescription: 'Animaciones y efectos visuales creativos. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Video y Animación.'
    },
    {
        id: 'synthesia_2351',
        name: 'Synthesia',
        sector: 'Video y Animación',
        logo: 'synthesia',
        emoji: '📽️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.synthesia.com',
        description: 'Videos corporativos con presentadores virtuales.',
        longDescription: 'Videos corporativos con presentadores virtuales. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Video y Animación.'
    },
    {
        id: 'invideo_7750',
        name: 'InVideo AI',
        sector: 'Video y Animación',
        logo: 'invideo',
        emoji: '🎥',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.invideo.com',
        description: 'Crea videos para YouTube/TikTok desde un prompt.',
        longDescription: 'Crea videos para YouTube/TikTok desde un prompt. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Video y Animación.'
    },
    {
        id: 'wonder_2097',
        name: 'Wonder Dynamics',
        sector: 'Video y Animación',
        logo: 'wonder',
        emoji: '🎞️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.wonder.com',
        description: 'Reemplaza personas por personajes 3D en video.',
        longDescription: 'Reemplaza personas por personajes 3D en video. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Video y Animación.'
    },
    {
        id: 'kaiber_7755',
        name: 'Kaiber',
        sector: 'Video y Animación',
        logo: 'kaiber',
        emoji: '📺',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.kaiber.com',
        description: 'Videos musicales y efectos de transformación.',
        longDescription: 'Videos musicales y efectos de transformación. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Video y Animación.'
    },
    {
        id: 'captionsai_6624',
        name: 'Captions.ai',
        sector: 'Video y Animación',
        logo: 'captionsai',
        emoji: '🎥',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.captionsai.com',
        description: 'Subtítulos automáticos y edición de clips virales.',
        longDescription: 'Subtítulos automáticos y edición de clips virales. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Video y Animación.'
    },
    {
        id: 'descript_6948',
        name: 'Descript',
        sector: 'Video y Animación',
        logo: 'descript',
        emoji: '📹',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.descript.com',
        description: 'Editor de video basado en texto (transcripción).',
        longDescription: 'Editor de video basado en texto (transcripción). Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Video y Animación.'
    },
    {
        id: 'github_8281',
        name: 'GitHub Copilot',
        sector: 'Programación',
        logo: 'github',
        emoji: '💻',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.github.com',
        description: 'Autocompletado de código líder.',
        longDescription: 'Autocompletado de código líder. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Programación.'
    },
    {
        id: 'replit_6127',
        name: 'Replit Agent',
        sector: 'Programación',
        logo: 'replit',
        emoji: '🔌',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.replit.com',
        description: 'Construye y despliega apps completas solo pidiéndolo.',
        longDescription: 'Construye y despliega apps completas solo pidiéndolo. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Programación.'
    },
    {
        id: 'boltnew_6272',
        name: 'Bolt.new',
        sector: 'Programación',
        logo: 'boltnew',
        emoji: '�️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.boltnew.com',
        description: 'Desarrollo web full-stack en el navegador.',
        longDescription: 'Desarrollo web full-stack en el navegador. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Programación.'
    },
    {
        id: 'v0dev_372',
        name: 'V0.dev',
        sector: 'Programación',
        logo: 'v0dev',
        emoji: '⚙️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.v0dev.com',
        description: 'Generación de interfaces (UI) en React.',
        longDescription: 'Generación de interfaces (UI) en React. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Programación.'
    },
    {
        id: 'lovable_8283',
        name: 'Lovable',
        sector: 'Programación',
        logo: 'lovable',
        emoji: '👩‍💻',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.lovable.com',
        description: 'Creación de aplicaciones web complejas sin código.',
        longDescription: 'Creación de aplicaciones web complejas sin código. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Programación.'
    },
    {
        id: 'anima_3712',
        name: 'Anima',
        sector: 'Programación',
        logo: 'anima',
        emoji: '💻',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.anima.com',
        description: 'Convierte diseños de Figma a código funcional.',
        longDescription: 'Convierte diseños de Figma a código funcional. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Programación.'
    },
    {
        id: 'blackbox_538',
        name: 'Blackbox AI',
        sector: 'Programación',
        logo: 'blackbox',
        emoji: '⚙️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.blackbox.com',
        description: 'Búsqueda y sugerencia de código ultra rápida.',
        longDescription: 'Búsqueda y sugerencia de código ultra rápida. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Programación.'
    },
    {
        id: 'tabnine_1076',
        name: 'Tabnine',
        sector: 'Programación',
        logo: 'tabnine',
        emoji: '�️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.tabnine.com',
        description: 'Alternativa privada para desarrollo empresarial.',
        longDescription: 'Alternativa privada para desarrollo empresarial. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Programación.'
    },
    {
        id: 'sourcegraph_6843',
        name: 'Sourcegraph Cody',
        sector: 'Programación',
        logo: 'sourcegraph',
        emoji: '⌨️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.sourcegraph.com',
        description: 'Asistente para entender bases de código gigantes.',
        longDescription: 'Asistente para entender bases de código gigantes. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Programación.'
    },
    {
        id: 'notion_9516',
        name: 'Notion AI',
        sector: 'Escritura y Productividad',
        logo: 'notion',
        emoji: '✍️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.notion.com',
        description: 'Gestión de proyectos y redacción integrada.',
        longDescription: 'Gestión de proyectos y redacción integrada. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'jasper_3064',
        name: 'Jasper',
        sector: 'Escritura y Productividad',
        logo: 'jasper',
        emoji: '📝',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.jasper.com',
        description: 'IA para marketing de contenidos y blogs.',
        longDescription: 'IA para marketing de contenidos y blogs. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'copyai_3982',
        name: 'Copy.ai',
        sector: 'Escritura y Productividad',
        logo: 'copyai',
        emoji: '📓',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.copyai.com',
        description: 'Redacción de textos de venta y anuncios.',
        longDescription: 'Redacción de textos de venta y anuncios. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'writesonic_6327',
        name: 'Writesonic',
        sector: 'Escritura y Productividad',
        logo: 'writesonic',
        emoji: '📝',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.writesonic.com',
        description: 'SEO y artículos optimizados para Google.',
        longDescription: 'SEO y artículos optimizados para Google. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'grammarly_3403',
        name: 'Grammarly AI',
        sector: 'Escritura y Productividad',
        logo: 'grammarly',
        emoji: '📋',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.grammarly.com',
        description: 'Corrector de estilo y tono avanzado.',
        longDescription: 'Corrector de estilo y tono avanzado. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'deepl_2698',
        name: 'DeepL Write',
        sector: 'Escritura y Productividad',
        logo: 'deepl',
        emoji: '🖋️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.deepl.com',
        description: 'Mejora la gramática y naturalidad en varios idiomas.',
        longDescription: 'Mejora la gramática y naturalidad en varios idiomas. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'gamma_3549',
        name: 'Gamma AI',
        sector: 'Escritura y Productividad',
        logo: 'gamma',
        emoji: '🖋️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.gamma.com',
        description: 'Generador automático de presentaciones (PPT).',
        longDescription: 'Generador automático de presentaciones (PPT). Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'beautifulai_5317',
        name: 'Beautiful.ai',
        sector: 'Escritura y Productividad',
        logo: 'beautifulai',
        emoji: '📚',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.beautifulai.com',
        description: 'Diseño de diapositivas inteligente.',
        longDescription: 'Diseño de diapositivas inteligente. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'otterai_314',
        name: 'Otter.ai',
        sector: 'Escritura y Productividad',
        logo: 'otterai',
        emoji: '✍️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.otterai.com',
        description: 'Transcripción y resumen de reuniones.',
        longDescription: 'Transcripción y resumen de reuniones. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'firefliesai_4489',
        name: 'Fireflies.ai',
        sector: 'Escritura y Productividad',
        logo: 'firefliesai',
        emoji: '✅',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.firefliesai.com',
        description: 'Graba y analiza videollamadas automáticamente.',
        longDescription: 'Graba y analiza videollamadas automáticamente. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'motion_722',
        name: 'Motion',
        sector: 'Escritura y Productividad',
        logo: 'motion',
        emoji: '✍️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.motion.com',
        description: 'Calendario inteligente que prioriza tus tareas.',
        longDescription: 'Calendario inteligente que prioriza tus tareas. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'reclaimai_9768',
        name: 'Reclaim.ai',
        sector: 'Escritura y Productividad',
        logo: 'reclaimai',
        emoji: '🖊️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.reclaimai.com',
        description: 'Optimización de agendas para equipos.',
        longDescription: 'Optimización de agendas para equipos. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Escritura y Productividad.'
    },
    {
        id: 'elicit_1899',
        name: 'Elicit',
        sector: 'Investigación y Datos',
        logo: 'elicit',
        emoji: '🧮',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.elicit.com',
        description: 'Automatiza la revisión de literatura académica.',
        longDescription: 'Automatiza la revisión de literatura académica. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Investigación y Datos.'
    },
    {
        id: 'sciteai_683',
        name: 'Scite.ai',
        sector: 'Investigación y Datos',
        logo: 'sciteai',
        emoji: '🧪',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.sciteai.com',
        description: 'Verifica citas y veracidad científica.',
        longDescription: 'Verifica citas y veracidad científica. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Investigación y Datos.'
    },
    {
        id: 'chatpdf_36',
        name: 'ChatPDF',
        sector: 'Investigación y Datos',
        logo: 'chatpdf',
        emoji: '🧮',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.chatpdf.com',
        description: 'Interactúa con cualquier archivo PDF.',
        longDescription: 'Interactúa con cualquier archivo PDF. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Investigación y Datos.'
    },
    {
        id: 'genei_3478',
        name: 'Genei',
        sector: 'Investigación y Datos',
        logo: 'genei',
        emoji: '📉',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.genei.com',
        description: 'Resumen de artículos y gestión de investigación.',
        longDescription: 'Resumen de artículos y gestión de investigación. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Investigación y Datos.'
    },
    {
        id: 'roseai_7791',
        name: 'Rose.ai',
        sector: 'Investigación y Datos',
        logo: 'roseai',
        emoji: '📊',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.roseai.com',
        description: 'Plataforma de datos económicos y financieros.',
        longDescription: 'Plataforma de datos económicos y financieros. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Investigación y Datos.'
    },
    {
        id: 'elevenlabs_3261',
        name: 'ElevenLabs',
        sector: 'Audio y Música',
        logo: 'elevenlabs',
        emoji: '🎙️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.elevenlabs.com',
        description: 'Clonación de voz y texto a voz realista.',
        longDescription: 'Clonación de voz y texto a voz realista. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Audio y Música.'
    },
    {
        id: 'adobe_9176',
        name: 'Adobe Podcast',
        sector: 'Audio y Música',
        logo: 'adobe',
        emoji: '🎧',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.adobe.com',
        description: 'Limpieza de audio profesional.',
        longDescription: 'Limpieza de audio profesional. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Audio y Música.'
    },
    {
        id: 'speechify_6979',
        name: 'Speechify',
        sector: 'Audio y Música',
        logo: 'speechify',
        emoji: '🎧',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.speechify.com',
        description: 'Convierte texto en audiolibros con voces naturales.',
        longDescription: 'Convierte texto en audiolibros con voces naturales. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Audio y Música.'
    },
    {
        id: 'moisesai_42',
        name: 'Moises.ai',
        sector: 'Audio y Música',
        logo: 'moisesai',
        emoji: '🥁',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.moisesai.com',
        description: 'Separa instrumentos y voces de canciones.',
        longDescription: 'Separa instrumentos y voces de canciones. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Audio y Música.'
    },
    {
        id: 'lalalai_7447',
        name: 'LALAL.AI',
        sector: 'Audio y Música',
        logo: 'lalalai',
        emoji: '🎤',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.lalalai.com',
        description: 'Extracción de pistas de audio (stems).',
        longDescription: 'Extracción de pistas de audio (stems). Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Audio y Música.'
    },
    {
        id: 'soundraw_2632',
        name: 'Soundraw',
        sector: 'Audio y Música',
        logo: 'soundraw',
        emoji: '🎸',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.soundraw.com',
        description: 'Música de fondo personalizable para creadores.',
        longDescription: 'Música de fondo personalizable para creadores. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Audio y Música.'
    },
    {
        id: 'voicemod_8700',
        name: 'VoiceMod',
        sector: 'Audio y Música',
        logo: 'voicemod',
        emoji: '🎷',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.voicemod.com',
        description: 'Transformación de voz en tiempo real.',
        longDescription: 'Transformación de voz en tiempo real. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Audio y Música.'
    },
    {
        id: 'zapier_7026',
        name: 'Zapier Central',
        sector: 'Automatización',
        logo: 'zapier',
        emoji: '🔁',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.zapier.com',
        description: 'Crea agentes que ejecutan tareas entre apps.',
        longDescription: 'Crea agentes que ejecutan tareas entre apps. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Automatización.'
    },
    {
        id: 'n8n_7803',
        name: 'n8n',
        sector: 'Automatización',
        logo: 'n8n',
        emoji: '🔂',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.n8n.com',
        description: 'Automatización técnica para desarrolladores.',
        longDescription: 'Automatización técnica para desarrolladores. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Automatización.'
    },
    {
        id: 'glean_7983',
        name: 'Glean',
        sector: 'Automatización',
        logo: 'glean',
        emoji: '🤖',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.glean.com',
        description: 'El buscador inteligente para datos internos de empresas.',
        longDescription: 'El buscador inteligente para datos internos de empresas. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Automatización.'
    },
    {
        id: 'mindos_8988',
        name: 'MindOS',
        sector: 'Automatización',
        logo: 'mindos',
        emoji: '🔁',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.mindos.com',
        description: 'Creación de agentes autónomos personalizados.',
        longDescription: 'Creación de agentes autónomos personalizados. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Automatización.'
    },
    {
        id: 'adcreativeai_3753',
        name: 'AdCreative.ai',
        sector: 'Marketing y Ventas',
        logo: 'adcreativeai',
        emoji: '🛒',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.adcreativeai.com',
        description: 'Generación de banners publicitarios.',
        longDescription: 'Generación de banners publicitarios. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Marketing y Ventas.'
    },
    {
        id: 'apolloai_7235',
        name: 'Apollo.ai',
        sector: 'Marketing y Ventas',
        logo: 'apolloai',
        emoji: '🛒',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.apolloai.com',
        description: 'Prospección de clientes y correos de ventas.',
        longDescription: 'Prospección de clientes y correos de ventas. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Marketing y Ventas.'
    },
    {
        id: 'ocoya_6624',
        name: 'Ocoya',
        sector: 'Marketing y Ventas',
        logo: 'ocoya',
        emoji: '📣',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.ocoya.com',
        description: 'Gestión de redes sociales y creación de posts.',
        longDescription: 'Gestión de redes sociales y creación de posts. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Marketing y Ventas.'
    },
    {
        id: 'brand24_4784',
        name: 'Brand24',
        sector: 'Marketing y Ventas',
        logo: 'brand24',
        emoji: '💸',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.brand24.com',
        description: 'Monitorización de reputación online.',
        longDescription: 'Monitorización de reputación online. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Marketing y Ventas.'
    },
    {
        id: 'typeform_1464',
        name: 'Typeform Formless',
        sector: 'Marketing y Ventas',
        logo: 'typeform',
        emoji: '🎯',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.typeform.com',
        description: 'Formularios conversacionales con IA.',
        longDescription: 'Formularios conversacionales con IA. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Marketing y Ventas.'
    },
    {
        id: 'topaz_3728',
        name: 'Topaz Video AI',
        sector: 'Utilidades',
        logo: 'topaz',
        emoji: '🗑️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.topaz.com',
        description: 'Restauración y escalado de video antiguo.',
        longDescription: 'Restauración y escalado de video antiguo. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'vectary_2296',
        name: 'Vectary',
        sector: 'Utilidades',
        logo: 'vectary',
        emoji: '🪛',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.vectary.com',
        description: 'Diseño y renderizado 3D.',
        longDescription: 'Diseño y renderizado 3D. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'nomic_3414',
        name: 'Nomic Atlas',
        sector: 'Utilidades',
        logo: 'nomic',
        emoji: '🛠️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.nomic.com',
        description: 'Visualización de grandes conjuntos de datos.',
        longDescription: 'Visualización de grandes conjuntos de datos. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'humata_2301',
        name: 'Humata AI',
        sector: 'Utilidades',
        logo: 'humata',
        emoji: '🔩',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.humata.com',
        description: 'Análisis de documentos técnicos legales o médicos.',
        longDescription: 'Análisis de documentos técnicos legales o médicos. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'tome_8028',
        name: 'Tome',
        sector: 'Utilidades',
        logo: 'tome',
        emoji: '🛠️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.tome.com',
        description: 'Narrativa visual y storytelling para empresas.',
        longDescription: 'Narrativa visual y storytelling para empresas. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'eightify_4539',
        name: 'Eightify',
        sector: 'Utilidades',
        logo: 'eightify',
        emoji: '⚙️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.eightify.com',
        description: 'Resúmenes instantáneos de videos de YouTube.',
        longDescription: 'Resúmenes instantáneos de videos de YouTube. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'monica_8048',
        name: 'Monica',
        sector: 'Utilidades',
        logo: 'monica',
        emoji: '🪛',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.monica.com',
        description: 'Extensión de navegador "todo en uno" (Chat + Resumen).',
        longDescription: 'Extensión de navegador "todo en uno" (Chat + Resumen). Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'hugging_8161',
        name: 'Hugging Face',
        sector: 'Utilidades',
        logo: 'hugging',
        emoji: '🪛',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.hugging.com',
        description: 'La biblioteca más grande de modelos de IA.',
        longDescription: 'La biblioteca más grande de modelos de IA. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'civitai_5754',
        name: 'Civitai',
        sector: 'Utilidades',
        logo: 'civitai',
        emoji: '🔨',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.civitai.com',
        description: 'Comunidad de modelos para Stable Diffusion.',
        longDescription: 'Comunidad de modelos para Stable Diffusion. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'poindexter_2523',
        name: 'Poindexter',
        sector: 'Utilidades',
        logo: 'poindexter',
        emoji: '🪛',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.poindexter.com',
        description: 'IA para proyecciones financieras de startups.',
        longDescription: 'IA para proyecciones financieras de startups. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'feedly_9345',
        name: 'Feedly Leo',
        sector: 'Utilidades',
        logo: 'feedly',
        emoji: '🔧',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.feedly.com',
        description: 'Curación de noticias impulsada por IA.',
        longDescription: 'Curación de noticias impulsada por IA. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'scribe_4342',
        name: 'Scribe',
        sector: 'Utilidades',
        logo: 'scribe',
        emoji: '⚙️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.scribe.com',
        description: 'Crea guías de usuario automáticas grabando tu pantalla.',
        longDescription: 'Crea guías de usuario automáticas grabando tu pantalla. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'heckfree_446',
        name: 'Heckfree',
        sector: 'Utilidades',
        logo: 'heckfree',
        emoji: '🪛',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.heckfree.com',
        description: 'Humanizador de textos generados por IA.',
        longDescription: 'Humanizador de textos generados por IA. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'did_4663',
        name: 'D-ID',
        sector: 'Utilidades',
        logo: 'did',
        emoji: '🔨',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.did.com',
        description: 'Animación de fotos para convertirlas en presentadores.',
        longDescription: 'Animación de fotos para convertirlas en presentadores. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'memai_3328',
        name: 'Mem.ai',
        sector: 'Utilidades',
        logo: 'memai',
        emoji: '🔩',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.memai.com',
        description: 'Organización de notas y conocimiento personal.',
        longDescription: 'Organización de notas y conocimiento personal. Explora más sobre esta herramienta en su sitio web ofical. Excelente solución en Utilidades.'
    },
    {
        id: 'make_1001',
        name: 'Make (Integromat)',
        sector: 'Automatización',
        logo: 'make',
        emoji: '🔄',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.make.com',
        description: 'Construye flujos de trabajo visuales y conecta miles de apps.',
        longDescription: 'La plataforma de automatización no-code más visual y potente. Permite conectar CRMs, correos, Inteligencia Artificial (OpenAI, Anthropic) y bases de datos para automatizar desde la atención al cliente hasta la facturación sin escribir una línea de código. Imprescindible para escalar operaciones en cualquier empresa.'
    },
    {
        id: 'zapier_1002',
        name: 'Zapier Central',
        sector: 'Automatización',
        logo: 'zapier',
        emoji: '⚡',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://zapier.com/central',
        description: 'Agentes de IA que ejecutan tareas en tus apps diarias.',
        longDescription: 'Central de Zapier te permite crear agentes de IA personalizados. Puedes chatear con la información de tus bases de datos y ordenar al agente que envíe correos, actualice registros en el CRM o cree reportes, usando los miles de integraciones de Zapier directamente desde una interfaz de chat.'
    },
    {
        id: 'chatbase_1003',
        name: 'Chatbase',
        sector: 'Chatbots y Asistentes',
        logo: 'chatbase',
        emoji: '💬',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.chatbase.co',
        description: 'Crea un chatbot para tu web entrenado con tus propios datos empresariales.',
        longDescription: 'Herramienta revolucionaria para atención al cliente. Sube los PDFs de tu empresa, enlaza tu sitio web completo o tu manual de usuario, y Chatbase creará un clon estilo ChatGPT que responde las dudas de tus clientes 24/7 de forma precisa y basándose únicamente en la información que tú le proporcionaste.'
    },
    {
        id: 'fireflies_1004',
        name: 'Fireflies.ai',
        sector: 'Escritura y Productividad',
        logo: 'fireflies',
        emoji: '🔥',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://fireflies.ai',
        description: 'Tu propio asistente que graba, transcribe y resume tus reuniones B2B.',
        longDescription: 'Se integra con Google Meet, Zoom y Teams. Entra a tus videollamadas comerciales, las transcribe en tiempo real, identifica quién habla, y al finalizar genera un resumen con las decisiones tomadas y las tareas pendientes (Action Items). Elimina la necesidad de tomar notas.'
    },
    {
        id: 'otterai_1005',
        name: 'Otter.ai',
        sector: 'Escritura y Productividad',
        logo: 'otter',
        emoji: '🦦',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://otter.ai',
        description: 'Asistente de reuniones en vivo e IA para colaboración de equipos comerciales.',
        longDescription: 'Además de transcribir reuniones corporativas con altísima precisión, OtterPilot se une a tus llamadas y genera notas detalladas. Incluye un bot en vivo al que le puedes preguntar "¿Qué dijo el cliente sobre el modelo de negocio hace 10 minutos?" durante la propia reunión.'
    },
    {
        id: 'clay_1006',
        name: 'Clay',
        sector: 'Marketing y Ventas',
        logo: 'clay',
        emoji: '🧱',
        isFullyFree: false,
        freeTierDetails: 'Prueba Gratis',
        url: 'https://www.clay.com',
        description: 'La hoja de cálculo dopada con IA para Outbound y prospección.',
        longDescription: 'Es el arma secreta de los equipos de ventas modernos. Conecta decenas de proveedores de datos (LinkedIn, Apollo, Google) en una sola tabla. Clay utiliza la IA para investigar a fondo cada uno de tus prospectos (leads) y redactar correos en frío hiperpersonalizados a escala masiva para cerrar gigantescos acuerdos.'
    },
    {
        id: 'gong_1007',
        name: 'Gong',
        sector: 'Marketing y Ventas',
        logo: 'gong',
        emoji: '🔔',
        isFullyFree: false,
        freeTierDetails: 'B2B Demo',
        url: 'https://www.gong.io',
        description: 'Inteligencia de ingresos (Revenue Intelligence) para equipos comerciales.',
        longDescription: 'Gong graba y analiza las llamadas y correos de tus vendedores. Mediante IA, detecta tendencias, objeciones comunes de clientes empresariales y evalúa si una negociación va por buen camino. Ofrece un panel directivo predictivo basado en la realidad temporal de las interacciones.'
    },
    {
        id: 'beautifulai_1008',
        name: 'Beautiful.ai',
        sector: 'Imagen y Diseño',
        logo: 'beautifulai',
        emoji: '📊',
        isFullyFree: false,
        freeTierDetails: 'Prueba Gratis',
        url: 'https://www.beautiful.ai',
        description: 'Software de presentaciones B2B corporativas que se auto-diseñan al momento.',
        longDescription: 'Ideal para B2B. A diferencia de un PowerPoint en blanco, esta herramienta aplica reglas de diseño inteligente. Solo necesitas agregar textos sobre tus ventas, el plan estratégico y gráficos financieros, y la plantilla se ajustará instantáneamente en un formato ultra corporativo y llamativo.'
    },
    {
        id: 'browseai_1009',
        name: 'Browse AI',
        sector: 'Investigación y Datos',
        logo: 'browseai',
        emoji: '🕵️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.browse.ai',
        description: 'Extrae y monitorea datos empresariales de la competencia sin saber programar.',
        longDescription: 'Permite conseguir listados de clientes y monitorear a tu competencia (precios) sin usar código complejo ni Python. Entrenas a un bot haciendo clics y BrowseAI se encargará de scrapear la web de tus competidores semanalmente e ingresarlo directamente en tus Google Sheets.'
    },
    {
        id: 'colossyan_1010',
        name: 'Colossyan Creator',
        sector: 'Video y Animación',
        logo: 'colossyan',
        emoji: '👨‍🏫',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.colossyan.com',
        description: 'Videos corporativos B2B usando actores realistas, ideal para RRHH.',
        longDescription: 'Una maravilla para el "onboarding" de tus empleados, soporte comercial y marketing corporativo (Linkedin). Simplemente pega el texto del manual de ventas de la empresa, selecciona a qué avatar quieres representar y producirás un video humano sin necesidad de equipos de rodaje.'
    },
    {
        id: 'lavender_1011',
        name: 'Lavender AI',
        sector: 'Marketing y Ventas',
        logo: 'lavender',
        emoji: '📧',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.lavender.ai',
        description: 'Asistente personal para redactar correos de venta (Cold Emails) infalibles.',
        longDescription: 'Este pequeño plugin vive en tu buzón y analiza cada correo destinado a "Conseguir un Cliente". Revisa milimétricamente el comportamiento para decirte qué debes borrar porque huele a "SPAM". Incluso explora en redes sociales la empresa de tu prospecto para proporcionarte un rompehielo a medida.'
    },
    {
        id: 'anyword_1012',
        name: 'Anyword',
        sector: 'Marketing y Ventas',
        logo: 'anyword',
        emoji: '📈',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://anyword.com',
        description: 'Redacta textos de anuncios online y predice cuánto convertirán de 1 a 100.',
        longDescription: 'El rey absoluto escribiendo copy publicitario y posts sociales orientados a vender. A diferencia de ChatGPT, Anyword genera decenas de textos B2B para MetaAds o Linkedin Ads y les incrusta una nota de rendimiento futuro para que sepas qué es más atractivo para tu demografía central.'
    },
    {
        id: 'mutiny_1013',
        name: 'Mutiny',
        sector: 'Marketing y Ventas',
        logo: 'mutiny',
        emoji: '🔀',
        isFullyFree: false,
        freeTierDetails: 'B2B Demo',
        url: 'https://www.mutinyhq.com',
        description: 'Mejora la conversión de tu sitio web personalizando el contenido por visitante.',
        longDescription: 'Mutiny detecta mágicamente si la visita en tu web B2B entra desde una mega-corporación o desde una startup en tiempo real. Acto seguido le hace un lifting a tu landing page y cambia los titulares a una propuesta específica que cautive a ese tipo de cliente concreto, aumentando la venta exponencialmente.'
    },
    {
        id: 'tome_1014',
        name: 'Tome',
        sector: 'Escritura y Productividad',
        logo: 'tome',
        emoji: '📚',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://tome.app',
        description: 'Informes de ventas, rondas de inversión (Pitch Decks) o métricas interactivas.',
        longDescription: 'Dile a Tome de qué trata tu idea de empresa y dejará obsoletas las viejas diapositivas tradicionales. Mediante la asistencia de Inteligencia Artificial generativa para tu negocio creará un pitch que encantará a inversores en forma de webs modulares atractivas para ganar tracción real.'
    },
    {
        id: 'alice_1015',
        name: '11x.ai (Alice)',
        sector: 'Marketing y Ventas',
        logo: '11x',
        emoji: '👩‍💼',
        isFullyFree: false,
        freeTierDetails: 'Demo',
        url: 'https://11x.ai',
        description: 'Representante de Ventas Digital, tu nueva empleada de prospección virtual.',
        longDescription: 'Alice y Charlie son modelos denominados "Trabajadores autónomos", que suplen el rol de un equipo Junior comercial. Buscan una empresa que cuadre en tu perfil de cliente, sacan a las personas importantes y conversan con ellas para conseguirte reuniones diarias directamente en el calendario.'
    },
    {
        id: 'akkio_1016',
        name: 'Akkio',
        sector: 'Investigación y Datos',
        logo: 'akkio',
        emoji: '📉',
        isFullyFree: false,
        freeTierDetails: 'B2B Promo',
        url: 'https://www.akkio.com',
        description: 'Ciencia de Datos y predicción analítica en la web para Pymes orientadas a SEO.',
        longDescription: 'Permite a directivos y responsables de Pymes subir tu hoja de bases de excel con los datos de cobros. Esta IA va a predecir resultados, agrupar y organizar clientes listos para convertir (Lead Scoring) y estimará tus ingresos sin necesitar tener un equipo científico ni ingenieros locales.'
    },
    {
        id: 'fathom_1017',
        name: 'Fathom',
        sector: 'Escritura y Productividad',
        logo: 'fathom',
        emoji: '🌊',
        isFullyFree: true,
        freeTierDetails: 'Gratis Total',
        url: 'https://fathom.video',
        description: 'Asistente virtual súper útil (para Zoom, Teams o Meet) que rellena tu CRM de ventas automáticamente.',
        longDescription: 'Conecta sus transcripciones con el software central de tu oficina. Este es uno de los mejores plugins de IA sin pagar debido a su facilidad y su naturaleza freemium perpetua en un principio. Graba silencioso, extrae la data necesaria, y actualiza Salesforce de forma inteligente sin molestias para ti.'
    },
    {
        id: 'brandmark_1018',
        name: 'Brandmark.io',
        sector: 'Imagen y Diseño',
        logo: 'brandmark',
        emoji: '🎯',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://brandmark.io',
        description: 'Crea tu Kit visual e imagen corporativa base a golpe de clic en tiempos récord.',
        longDescription: 'Destinada a start-ups recién nacidas o side-projects, con la ayuda de un motor inteligente produce paletas, logos comerciales, firmas, papeles de recibo, perfiles para redes orientadas en la gama. No requiere que el negocio pague a especialistas durante la dura etapa exploratoria inicial de mercado.'
    },
    {
        id: 'attention_1019',
        name: 'Attention.tech',
        sector: 'Marketing y Ventas',
        logo: 'attention',
        emoji: '🔍',
        isFullyFree: false,
        freeTierDetails: 'Demo',
        url: 'https://www.attention.tech',
        description: 'Coaching para comerciales y chivatazo de IA sobre qué y cómo contestar a una objeción de venta.',
        longDescription: 'Imprescindible para entornos muy competitivos; al integrarlo las videollamadas con cliente son escaneadas por Attention que envía por pantalla al vendedor textos (scripts o cartas) idóneas a lo que detecta del prospecto. Al final transfiere de forma impecable esas minutas al centro (CRM).'
    },
    {
        id: 'retellai_1020',
        name: 'Retell AI',
        sector: 'Chatbots y Asistentes',
        logo: 'retellai',
        emoji: '📞',
        isFullyFree: false,
        freeTierDetails: 'Demo / API',
        url: 'https://www.retellai.com',
        description: 'Voces de agentes ultra-realistas destinadas al sector atención y captura de B2B telefónico.',
        longDescription: 'Construye la infraestructura para crear llamadas al cliente idénticas a un ser orgánico pero 100% automatizadas. Tus flujos capturan clientes, le sacan detalles extra sin retraso o lag audible en milésimas de segundo aportando un soporte en forma y escala para grandes niveles de clientes activos.'
    },
    {
        id: 'elevenlabs_2001',
        name: 'ElevenLabs',
        sector: 'Audio y Música',
        logo: 'elevenlabs',
        emoji: '🎙️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://elevenlabs.io',
        description: 'El mejor generador de voces clonadas y Text-to-Speech del mercado con un realismo aterrador.',
        longDescription: 'Líder indiscutible en síntesis de voz. Puedes clonar tu propia voz leyendo unos minutos de texto, o usar cientos de perfiles que respiran, varían la entonación y transmiten emoción de forma hiperrealista. Ideal para audiolibros, canales de YouTube sin rostro y videojuegos.'
    },
    {
        id: 'opusclip_2002',
        name: 'OpusClip',
        sector: 'Video y Animación',
        logo: 'opusclip',
        emoji: '✂️',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.opus.pro',
        description: 'Transforma podcasts largos en docenas de clips virales cortos (Shorts/Reels) automáticamente.',
        longDescription: 'Conecta la URL de tu video largo de YouTube y OpusClip usará IA predictiva para encontrar los momentos de mayor retención (las mejores frases), recortarlos al formato vertical 9:16 y añadirles subtítulos dinámicos estilo Alex Hormozi con una puntuación de viralidad. Ahorra 10 horas de edición manual.'
    },
    {
        id: 'deepl_2003',
        name: 'DeepL Translate / Write',
        sector: 'Escritura y Productividad',
        logo: 'deepl',
        emoji: '🌐',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.deepl.com',
        description: 'El traductor y conector lógico de textos más preciso de toda la web, superior a Google.',
        longDescription: 'Basado en redes neuronales profundas (Deep Learning) que captan el contexto humano. Su herramienta "DeepL Write" incluye corrección de estilo para asegurar que tu inglés o alemán no suenen extraños. Utilizado por miles de corporaciones de ámbito internacional por salvaguardar matices y jerga técnica.'
    },
    {
        id: 'grammarly_2004',
        name: 'Grammarly',
        sector: 'Escritura y Productividad',
        logo: 'grammarly',
        emoji: '✅',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.grammarly.com',
        description: 'Asistente de gramática omnipresente y reescritura de correos según el tono.',
        longDescription: 'El plugin más instalado para profesionales. No solo corrige faltas de ortografía, ahora la IA lee todo tu correo y con un clic lo "suaviza", lo hace "más confidencial" o "más persuasivo". Evita que uses vocabulario aburrido y mide tu legibilidad general de manera continua.'
    },
    {
        id: 'surferseo_2005',
        name: 'Surfer SEO',
        sector: 'Marketing y Ventas',
        logo: 'surferseo',
        emoji: '📈',
        isFullyFree: false,
        freeTierDetails: 'Solo Pago',
        url: 'https://surferseo.com',
        description: 'Te dicta las palabras exactas que debes usar para que Google te ponga en la página 1.',
        longDescription: 'La obsesión de los especialistas del marketing digital. Surfer lee en vivo los 10 primeros resultados de Google para tu búsqueda y te da una puntuación (del 1 al 100) mientras redactas en su editor. Te dice cosas como "Te faltan 3 repeticiones de la palabra servidor". Literalmente optimiza el contenido antes de que le des a publicar.'
    },
    {
        id: 'rytr_2006',
        name: 'Rytr',
        sector: 'Escritura y Productividad',
        logo: 'rytr',
        emoji: '✍🏼',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://rytr.me',
        description: 'Generador y asistente de textos (Copywriting) rápido y muy económico.',
        longDescription: 'Mientras otros cobran suscripciones altísimas, Rytr te da un tier gratuito amplio para redactar descripciones de producto, respuestas a reseñas furiosas o emails de campaña comercial. Seleccionas el tono (alegre, formal, inspirador...), apuntas la idea y él plasma un párrafo bien estructurado.'
    },
    {
        id: 'photoroom_2007',
        name: 'Photoroom',
        sector: 'Imagen y Diseño',
        logo: 'photoroom',
        emoji: '👕',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.photoroom.com',
        description: 'Estudio fotográfico virtual para vender productos online. Edición brutal por IA.',
        longDescription: 'Líder en comercio electrónico (Vinted, Shopify, Amazon). Hazle una foto rápida a tus zapatillas y la IA quita el fondo de cartón de tu cama, aplica sombras de calidad de estudio profesional, modifica la luz y lo sitúa, por ejemplo, encima de una piedra preciosa sobre un fondo blanco.'
    },
    {
        id: 'removebg_2008',
        name: 'Remove.bg',
        sector: 'Utilidades',
        logo: 'removebg',
        emoji: '🪄',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.remove.bg',
        description: 'La magia instantánea y 100% gratuita para quitarle el fondo a cualquier foto.',
        longDescription: 'Con 1 solo clic y en 4 segundos tu imagen aparecerá sin fondo (transparente en PNG). Distingue a la perfección el pelo desordenado, pelaje de animales o superficies semitransparentes. Un mini-salvavidas diario para todo generador de portadas o presentaciones que necesita imágenes listas ya.'
    },
    {
        id: 'ideogram_2009',
        name: 'Ideogram',
        sector: 'Imagen y Diseño',
        logo: 'ideogram',
        emoji: '🔤',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://ideogram.ai',
        description: 'El mejor en "escribir texto" dentro de la propia imagen generada.',
        longDescription: 'Durante años las IAs inventaban letras locas en carteles. Ideogram introdujo un modelo impecable para que pongas frases exactas (ej: cartel de neón que diga "Abierto"). Brutal diseñando logotipos con el nombre correcto de tu web, sudaderas, tazas de desayuno o gráficos vectoriales.'
    },
    {
        id: 'playground_2010',
        name: 'Playground AI',
        sector: 'Imagen y Diseño',
        logo: 'playground',
        emoji: '🛝',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://playground.com',
        description: 'Plataforma para generar imágenes increíbles iterando creativamente sobre un canvas gigante.',
        longDescription: 'Su increíble plan gratuito te daba la barbaridad de cientos de imágenes gratis al día. Dispone de un lienzo donde puedes modificar elementos de una foto o mezclar diferentes fotografías existentes en vivo, borrando sujetos a placer con la mayor precisión.'
    },
    {
        id: 'youcom_2011',
        name: 'You.com',
        sector: 'Investigación y Datos',
        logo: 'youcom',
        emoji: '🔎',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://you.com',
        description: 'Buscador centrado en privacidad e IA con selección multimodal.',
        longDescription: 'No te rastrea para publicidad y proporciona resultados sumados y explicados mediante inteligencia artificial en una interfaz fresca. Su plan Pro te deja escoger con solo un clic qué IA responde (puedes alternar entre GPT-4, Claude 3 o Mistral al vuelo para probar enfoques diferentes).'
    },
    {
        id: 'elicit_2012',
        name: 'Elicit',
        sector: 'Investigación y Datos',
        logo: 'elicit',
        emoji: '🎓',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://elicit.com',
        description: 'Mano derecha para universitarios y médicos en investigación de Papers.',
        longDescription: 'Le preguntas a Elicit algo como "¿Cura la melatonina el insomnio?" y buscará exclusivamente en miles de ensayos clínicos y artículos académicos indexados. Creará una tabla sintética respondiendo qué dicen esos papers evitando toda posibilidad de alucinaciones.'
    },
    {
        id: 'speechify_2013',
        name: 'Speechify',
        sector: 'Audio y Música',
        logo: 'speechify',
        emoji: '🎧',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://speechify.com',
        description: 'Lector automático de PDFs, correos de trabajo y webs completas con increíbles voces.',
        longDescription: 'Imprescindible para la accesibilidad, personas con TDAH o quienes hacen multitarea conduciendo. Hace que tu ordenador o móvil te lea literalmente hasta las facturas en audios tan entretenidos como un podcast y hasta usando las voces de Snoop Dogg o Gwyneth Paltrow.'
    },
    {
        id: 'adobepodcast_2014',
        name: 'Adobe Podcast Enhance',
        sector: 'Audio y Música',
        logo: 'adobepodcast',
        emoji: '🎤',
        isFullyFree: true,
        freeTierDetails: '100% Gratis',
        url: 'https://podcast.adobe.com/enhance',
        description: 'Repara gratis los ecos o ruidos de tu voz como si usaras un micrófono de cadena de radio cara.',
        longDescription: 'Puedes tener una videollamada desde el medio de la calle en pleno temporal. Si subes aquí tu pista de audio, este brutal modelo de Adobe eliminará mágicamente a la gente, el viento o el ruido del ordenador restando pureza al discurso como si estuvieses en un estudio acolchado de Hollywood.'
    },
    {
        id: 'fliki_2015',
        name: 'Fliki',
        sector: 'Video y Animación',
        logo: 'fliki',
        emoji: '📝',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://fliki.ai',
        description: 'Pega el texto de tu entrada de blog y Fliki creará un video completamente montado.',
        longDescription: 'No todo el mundo quiere usar cámaras, este Text-to-Video es comodísimo. Vas montando las escenas escribiendo qué dice el narrador de fondo, y él se nutre de bibliotecas gigantescas (Stock) buscando clips acordes al tema, los entrelaza y añade subtítulos a tu gusto. Súper dinámico.'
    },
    {
        id: 'pictory_2016',
        name: 'Pictory',
        sector: 'Video y Animación',
        logo: 'pictory',
        emoji: '🎞️',
        isFullyFree: false,
        freeTierDetails: 'Prueba Gratis',
        url: 'https://pictory.ai',
        description: 'Reúne las partes más intensas del discurso o webinario aburridos en "momentazos" comerciales (Teaser).',
        longDescription: 'Se alimenta de enormes conferencias corporativas por Zoom (1-2 horas), saca la transcripción completa para que en su panel subrayes como con un rotulador las frases clave. Entonces la IA coge esas partes aisladas, borra los uhmm\'s y vacíos, y escupe tres minutos dinámicos para promocionarte en YouTube y LinkedIn.'
    },
    {
        id: 'codeium_2017',
        name: 'Codeium',
        sector: 'Programación',
        logo: 'codeium',
        emoji: '🧑‍💻',
        isFullyFree: true,
        freeTierDetails: 'Extensión Gratis!',
        url: 'https://codeium.com',
        description: 'El archienemigo OpenSource de GitHub Copilot; extensión IA para IDE (VS Code).',
        longDescription: 'Autocompleta de manera muy robusta docenas de lenguajes pero totalmente enfocado a ser la alternativa gratuita universal a Copilot. Incorpora su propio modelo que predice y completa bloques lógicos, reduce un 40% el tiempo rellenando Boilerplate (el "código sucio" obligatorio).'
    },
    {
        id: 'phind_2018',
        name: 'Phind',
        sector: 'Programación',
        logo: 'phind',
        emoji: '🐛',
        isFullyFree: false,
        freeTierDetails: 'Búsqueda Ilimitada',
        url: 'https://www.phind.com',
        description: 'Tu ingeniero Senior o colega de mesa: buscador que encuentra y digiere documentación de IT.',
        longDescription: 'Google ha quedado obsoleto al buscar fallos extraños de Rust o la última versión de React. Le copias a Phind tu error (Exception) y va peinando la red en tiempo real leyendo hilos crípticos de Github o StackOverflow hasta compilar la solución 10/10 presentándotela con su respectivo código.'
    },
    {
        id: 'superhuman_2019',
        name: 'Superhuman AI',
        sector: 'Escritura y Productividad',
        logo: 'superhuman',
        emoji: '🦸',
        isFullyFree: false,
        freeTierDetails: 'Acceso Élite',
        url: 'https://superhuman.com',
        description: 'El gestor de correos más rápido (e IA-infiltrado) hecho nunca con atajos ninja y resúmenes.',
        longDescription: 'Usado con fervor por los CEO europeos. En vez de leer esas odiosas interminablemente largas cadenas de hilos de correos de un cliente, pide a Superhuman que escriba 3 balas (bullets) esquemáticas o presiona atajos de teclado para que responda a 5 reuniones proponiendo el lunes.'
    },
    {
        id: 'pi_2020',
        name: 'Pi (Inflection AI)',
        sector: 'Chatbots y Asistentes',
        logo: 'pi_ai',
        emoji: '🤝',
        isFullyFree: true,
        freeTierDetails: 'Gratis Total',
        url: 'https://pi.ai',
        description: 'Curioso y amigable: el Chatbot diseñado para no dar respuestas frías y escuchar tus emociones de forma genuina.',
        longDescription: 'Mientras que a GPT-4 le das una orden mecánica; con Pi creas un vínculo. Nunca trata de cortarte rápido ni soltar un párrafo genérico corporativo. Está entrenado para entender de psicología, debatir en base al feedback positivo y ser un confidente o coach para desahogarse de forma personal.'
    },
    {
        id: 'frase_2021',
        name: 'Frase.io',
        sector: 'Marketing y Ventas',
        logo: 'frase',
        emoji: '🔬',
        isFullyFree: false,
        freeTierDetails: 'Prueba de 5 días',
        url: 'https://www.frase.io',
        description: 'Agiliza tu proceso SEO elaborando el esqueleto de tu artículo analizando la competencia con IA.',
        longDescription: 'Antes de escribir nada tu negocio, le das el tema a Frase ("Cómo arreglar un motor V8") y crea el "briefing" (esquema o borrador) trayendo todas las FAQs, H2s y subtítulos perfectos extrayéndolo de datos del motor de búsqueda central analizados por la inteligencia artificial.'
    },
    {
        id: 'slidesai_2022',
        name: 'SlidesAI',
        sector: 'Escritura y Productividad',
        logo: 'slidesai',
        emoji: '📊',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.slidesai.io',
        description: 'Aplicación interna de Google que fabrica diapositivas en Google Slides absorbiendo un Docs entero.',
        longDescription: 'Súper nicho para escuelas, empresas y agencias ágiles: En lugar de usar una app remota, abres tu viejo archivo de Google presentaciones y con un click en esta extensión oficial extrae viñetas o esquemas de tus pesados manuales montando cada slide para tí al instante.'
    },
    {
        id: 'scholarcy_2023',
        name: 'Scholarcy',
        sector: 'Investigación y Datos',
        logo: 'scholarcy',
        emoji: '📚',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.scholarcy.com',
        description: 'Biblioteca mágica que se "harta" a leer largos PDFs destriptando referencias e hipótesis.',
        longDescription: 'Excelente en niveles universitarios de posgrados. Vas subiendo PDF mastodónticos de los ministerios y esta IA los va a transformar en un sistema estandarizado de visuales (tarjetas o Flashcards con enlaces rápidos). Facilita una brutal velocidad a investigadores del área de tesis doctoral.'
    },
    {
        id: 'murf_2024',
        name: 'Murf.ai',
        sector: 'Audio y Música',
        logo: 'murf',
        emoji: '📣',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://murf.ai',
        description: 'Libreria inmensa de voces naturales que saben que venden o imparten e-learning en diferentes tonalidades audibles.',
        longDescription: 'Es el estándar para B2B e instructores locales e-learning y comerciales de YouTube Ads. Puesto que no todos quieren voces infantiles ni serias; aquí eliges concretamente si es voz publicitaria en español hispano entusiasta, acentos franceses suaves de lujo, etc. Todo un estudio para voz en Off.'
    },
    {
        id: 'webflow_2025',
        name: 'Webflow AI',
        sector: 'Imagen y Diseño',
        logo: 'webflow',
        emoji: '🌐',
        isFullyFree: false,
        freeTierDetails: 'Funciona Integrada',
        url: 'https://webflow.com/ai',
        description: 'Diseño al milímetro con interfaz arrastrar y soltar superpotenciado por asistente IA embebido directametne en CSS.',
        longDescription: 'Webflow, considerado el Rolls Royce del diseño Web profesional se acopló con IA para facilitar a los que no programan: Le dices "añade un sombreado o diseña una nueva paleta que transmita calma en estas cajas", y la IA reescribe en vivo las variables de su entorno visual gráfico (CSS).'
    },
    {
        id: 'playht_2026',
        name: 'Play.ht',
        sector: 'Audio y Música',
        logo: 'playht',
        emoji: '🗣️',
        isFullyFree: false,
        freeTierDetails: 'Freemium (Palabras Libres)',
        url: 'https://play.ht',
        description: 'Voces extremadamente versátiles y con API masiva perfectas para locuciones periodísticas intensas o ficción lúdica.',
        longDescription: 'Considerado el gemelo de ElevenLabs. Puedes elegir a un abuelito rasposo narrando cuentos o al narrador documental épico para ciencia ficción. Cuentan con unas dinámicas audibles donde las risitas ahogadas o respiros naturales entre comas desdibujan lo robótico con lo empíricamente humano.'
    },
    {
        id: 'amazonq_2027',
        name: 'Amazon Q Developer',
        sector: 'Programación',
        logo: 'amazonq',
        emoji: '📦',
        isFullyFree: false,
        freeTierDetails: 'Developer Free',
        url: 'https://aws.amazon.com/q/developer',
        description: 'La gran IA del imperio Bezos para desarrolladores centrados en el inmenso mundo AWS Cloud Services.',
        longDescription: 'Antes "CodeWhisperer". Su gran ventaja sobre Copilot de Github es el entendimiento profundo, exhaustivo y radical a la hora de resolver, escanear la seguridad e inventar configuraciones de servidores en Amazon (Cloud/IaaS). Perfecto dev B2B Cloud. Además asume las reparaciones a la primera directiva.'
    },
    {
        id: 'whisper_2028',
        name: 'Whisper (OpenAI)',
        sector: 'Audio y Música',
        logo: 'whisper',
        emoji: '🔊',
        isFullyFree: true,
        freeTierDetails: '100% Free y OpenSource',
        url: 'https://openai.com/research/whisper',
        description: 'Entiende voces que ni tú entenderías debido a ruidos externos y es el rey de Open-Source.',
        longDescription: 'Transcribe a texto sin piedad audios kilométricos independientemente de idiomas marginales. Está descargable en Python, e integrado gratis con interfaces como MacWhisper, lo cual lo empuja sobre la mesa como uno de los pilares libres o gratuitos con los usos más diarios de toda esta la revolución digital actual.'
    },
    {
        id: 'munch_2029',
        name: 'Munch',
        sector: 'Video y Animación',
        logo: 'munch',
        emoji: '🍿',
        isFullyFree: false,
        freeTierDetails: 'Freemium',
        url: 'https://www.getmunch.com',
        description: 'Destruye videos mega-largos corporativos y detectará instantes de emoción o comedia para las plataformas rápidas (TikTok/Instagram).',
        longDescription: 'A diferencia de editores crudos; Munch tiene integrados conectores para SEO. Si la IA detecta a tu invitado hablar sobre "Dopamina para crecer"; lo extraerá y Munch dirá: "Deberías viralizarlo en TikTok hoy porque las palabras de Dopamina están de moda" todo en vertical. Es una gran herramienta de marketing.'
    },
    {
        id: 'xembly_2030',
        name: 'Xembly',
        sector: 'Horarios',
        logo: 'xembly',
        emoji: '📅',
        isFullyFree: false,
        freeTierDetails: 'Trial/Demo',
        url: 'https://www.xembly.com',
        description: 'Director de orquesta. Te automatiza citas con otros humanos negociando fechas vía email (Agente de Calendario)',
        longDescription: 'Dile a tu asistente (Xena - en Slack o Mails) "Oye, reúnete con el cliente tal el martes o miércoles". La IA mandará mails al cliente como si fueses tú buscando disponibilidad, negocia amablemente por horas exactas en todas las zonas horarias del mundo cerrando la invitación directamente en las agendas de los dos individuos.'
    }
];

export const categories = ['Todos', 'Chatbots y Asistentes', 'Imagen y Diseño', 'Video y Animación', 'Programación', 'Escritura y Productividad', 'Investigación y Datos', 'Audio y Música', 'Automatización', 'Marketing y Ventas', 'Utilidades', 'Cocina', 'Horarios', 'Moda'];
